### ISSUE TITLE
Get multiple lists 'totalSubscribers' with ForEach get random results

### ISSUE THREAD

**Issue by starkhub** [sendinblue/APIv3-php-library#100]
Hello,

I need to get multiple lists 'totalSubscribers' number.

I write this piece of php code :

`$apiInstance = new SendinBlue\Client\Api\ContactsApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client(),
    $config
);
$listIds = array(32,26,36,28,29,30,31,27,33,14,38,44,47,46,45,43,42,41,40,39); // int | Id of the list
$file = "results.csv";
$fileContent = "";
try {

    foreach($listIds as &$ID){
        $result = $apiInstance->getList($ID);
        $obj = json_decode($result);
        $fileContent .=($obj->{'totalSubscribers'} . ',');
    }
    file_put_contents($file, $fileContent, LOCK_EX);

} catch (Exception $e) {
    echo 'Exception when calling ContactsApi->getList: ', $e->getMessage(), PHP_EOL;
}`

It's working but give me random wrong results like : 

29,0,0,1,0,0,21,0,0,1325,0,0,0,0,0,0,0,0,23236,0,

29,0,0,1,0,0,21,2,0,6427,0,0,0,0,0,0,0,0,0,0,

29,0,0,1,0,0,21,2,0,0,0,0,0,0,0,0,0,0,0,0,

There's something I'm doing wrong ? 

Thanks you in advance.

**Comment by rajatsib** [comment]
Hello @starkhub 

This is happening because you are sending multiple requests at the same time The request which gets the response first will be displayed first.

If you want to maintain the order, you have to wait for the response of the first list before htting the request for next list.
