### ISSUE TITLE
invalid_parameter 

### ISSUE THREAD

**Issue by Vivekdigitalguru** [sendinblue/APIv3-php-library#102]
while  creating the contact we have received this error 

Client error: `POST https://api.sendinblue.com/v3/contacts` resulted in a `400 Bad Request` response: {"code":"invalid_parameter","message":"Transactional attribute as primary Key is missing"}

**Comment by loicmartinmaniaki** [comment]
Hello I had this error when I had fields in attribute that were not present in sendinblue, try to minimize the number of fields in attribute to see if it comes from there.

**Comment by rajatsib** [comment]
Hi @Vivekdigitalguru 

This error occurs when you are passing transactional attributes but none of them had **id** while creating the attribute
