### ISSUE TITLE
Cannot install on PHP 7.2 (FriendsOfPHP / PHP-CS-Fixer requires <7.2)

### ISSUE THREAD

**Issue by devconfirm** [sendinblue/APIv3-php-library#110]
Composer install errors out with: 
    
> - Installation request for friendsofphp/php-cs-fixer v1.13.3 -> satisfiable by friendsofphp/php-cs-fixer[v1.13.3].
>     - friendsofphp/php-cs-fixer v1.13.3 requires php ^5.3.6 || >=7.0 <7.2 -> your PHP version (7.2.29) does not satisfy that requirement.

Current friendsofphp/php-cs-fixer is at v2.16 which should work with PHP 7.2. How can I make API v3 work with a newer version of php-cs-fixer so the installation on PHP 7.2 does not fail? Thank you.

**Comment by rajatsib** [comment]
Hi @devconfirm 

The above issue occured on using an older version of php-cs-fixer as it requires PHP verison <7.2
There is no issue in installing php-cs-fixer v2.16 on PHP 7.2 or greater with api-v3-sdk

Thanks
