### ISSUE TITLE
Double opt in doesn't work - Redirection issues

### ISSUE THREAD

**Issue by itsdun** [sendinblue/APIv3-php-library#112]
Hi sendinblue Team,

the double opt in feature is not working for me. The email is sent correctly to the given email address, but when i click the confirmation-button inside mail, i get a blank page and a error in chrome console: Uncaught DOMException: Failed to set the 'href' property on 'Location': 'http://' is not a valid URL.
    at HTMLIFrameElement.onload 

I've played around with different redirectionUrls and also without this parameter, no success.

Code:

```php
$apiInstance = new \SendinBlue\Client\Api\ContactsApi(
    new \GuzzleHttp\Client(),
    $config
);
$createDoiContact = new \SendinBlue\Client\Model\CreateDoiContact(
    [
        'email' => 'mail@example.com',
        'redirectionUrl' => '<url>',
        'includeListIds' => [2],
        'templateId' => 2,
    ]
);
try {
    $apiInstance->createDoiContact($createDoiContact);
} catch (\Exception $e) {
    echo $e->getMessage(), PHP_EOL;
}
```
Regards,
Marco

**Comment by chrisdicarlo** [comment]
Similar issue here.  Clicking the link in the button in the email registers the click on the dashboard but I immediately get redirected to a page that doesn't exist and the contact never gets added to the list.

**Comment by kevinley** [comment]
Hello,

Pinging @jamalofski @shubhamUpadhyayInBlue @ekta-slit @rajatsib 

I have the same issue:

- After createDoiContact I receive the email with the confirmation link.
- Clicking on the button in the email opens the browser showing
```
cijegjf.r.af.d.sendibt2.com sent an invalid response.
ERR_INVALID_REDIRECT
```
- In my sendinblue account, the contact is NOT created and NOT added to the desired list.

This feature is very important and urgent to me.

**Comment by pagelab** [comment]
Please. Can we get a weight on this issue or, at least, some feedback? The issue even occurs using the Curl example [from your own API reference](https://developers.sendinblue.com/reference#createdoicontact)... This definitely needs more attention.

**Comment by JHeimbach** [comment]
I opened a ticket in the sendinblue application and got the following answer, which worked for me:

 - send a request with redirectionUrl (otherwise it still does not work) 
 - set the doi link in your template to `{{ params.DOIurl }}`

**Comment by skynetsib** [comment]
Hi @itsdun ,
Please use the variable `{{ params.DOIurl }}` in your template as mentioned here.
https://developers.sendinblue.com/reference#createdoicontact

**Comment by kevinley** [comment]
@skynetsib When I change {{ doubleoptin }} to {{ params.DOIurl }}, I cannot select the template in the sendinblue wordpress plugin anymore. I get this error message:
```
The chosen template does not contain a [DOUBLEOPTIN] link that allows registrants to confirm their registration.
You must modify your template to include the [DOUBLEOPTIN] shortcode instead of a URL before you can choose it.
```

**Comment by kevinley** [comment]
@skynetsib Where do we have to use {{ params.DOIurl }} exactly ?
[Here](https://help.sendinblue.com/hc/en-us/articles/208771869-Create-a-subscription-form) in the point 4.3.a it's mentioned that {{ doubleoptin }} must be used, I can confirm that I am not even able to select the Default Double optin template in the sendinblue wordpress plugin when {{ doubleoptin }} is not present in the template..

**Comment by rajatsib** [comment]
Hi @kevinley 

First to create a DOI template

 You will need to add an 'optin' tag in the template setup.
You will also need to specify which CTA in your template design follows to the actual confirmation, for this you need to setup the {{ doubleoptin }} placeholder in your CTA link or button.

To create a contact through DOI flow 

You will need to replace the {{ doubleoptin }} with {{ params.DOIurl }} in your DOI template design in case you want to specify a custom redirection URL once your contact clicks the CTA. DOIurl is passed as an attribute in the API call and then embedded to the {{params.DOIurl}} placeholder.

You can find more info on this [here](https://developers.sendinblue.com/docs/other-common-questions#how-to-create-contact-via-doi-double-opt-in-flow-using-the--api-endpoint)
