### ISSUE TITLE
RequestSmsRecipientExport PSR-4 issue

### ISSUE THREAD

**Issue by MIvanIsten** [sendinblue/APIv3-php-library#113]
Deprecation Notice: Class SendinBlue\Client\Model\RequestSmsRecipientExport located in /vendor/sendinblue/api-v3-sdk/lib/Model/RequestSMSRecipientExport.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

File name should match class name. SMS != Sms

**Comment by georgringer** [comment]
so will this be merged?
