### ISSUE TITLE
Api v3 laravel

### ISSUE THREAD

**Issue by tomaswarynyca** [sendinblue/APIv3-php-library#115]
Hello, could you add documentation to incorporate the api v3 into laravel?

**Comment by L00Cyph3r** [comment]
This is a bare-bones PHP library, for integration into different libraries/platforms you need to dive deep or google for some package that already does what you want.  
I think you are looking for something like this: https://github.com/agence-webup/laravel-sendinblue

**Comment by ybert** [comment]
I think the package from webup is only for TransactionalEmailsApi . 

If you want full integration it is very simple with Laravel.
First, create a ServiceProvider : 
```
<?php


namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use SendinBlue\Client\Api\ContactsApi;
use SendinBlue\Client\Configuration;

class SendinBlueServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(ContactsApi::class, function ($app) {
            $config = Configuration::getDefaultConfiguration()->setApiKey($app['config']['services.sendinblue.key_identifier'], $app['config']['services.sendinblue.key']);

            return new ContactsApi(
                null,
                $config
            );
        });
    }
}
```

You can add a singleton for each api you want to be injected automatically in your code.

Then register your service provider in app.php inside the providers array : 
`App\Providers\SendinBlueServiceProvider::class,`

Finally, don't forget to add config vars in config/services.php : 
`    'sendinblue' => [
        'key_identifier' => 'api-key',
        'key' => env('SENDINBLUE_API_KEY')
    ],`

**Comment by Hesesses** [comment]
+1 for laravel support

**Comment by rajatsib** [comment]
Hi @tomaswarynyca @Hesesses 

This is a barebones PHP SDK. Currently, there is no laravel wrapper for this.
Can you try to implement the [solution](https://github.com/sendinblue/APIv3-php-library/issues/115#issuecomment-772951465) mentioned by @ybert

**Comment by rajatsib** [comment]
Hi @tomaswarynyca @Hesesses @ybert 

Closing this issue as this is a barebones PHP SDK.
You can write your own laravel implementation for this.

Thanks
