### ISSUE TITLE
Invalid version string ^v2017

### ISSUE THREAD

**Issue by gdidelot** [sendinblue/APIv3-php-library#118]
On executing command : composer require sendinblue/api-v3-sdk "6.4.0"
The error occured is :

[RuntimeException]
  Could not load package bp-ws/laravel-netsuite-ws in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^v2017: Invalid version str
  ing "^v2017"

  [UnexpectedValueException]
  Could not parse version constraint ^v2017: Invalid version string "^v2017"

**Comment by rajatsib** [comment]
Hi @gdidelot 

This is most probably a problem with loading bp-ws/laravel-netsuite-ws and not the sendinblue SDK.

Thanks
