### ISSUE TITLE
Send an email?

### ISSUE THREAD

**Issue by stevesmithworks** [sendinblue/APIv3-php-library#119]
Hi,

I've used an old API v2 client in a file called Mailin.php. Things were quite easy to send a simple email by specifying to, from, subject, and html body.

Now I'm trying to use the API v3 and having trouble. I can follow the [getting started example](https://github.com/sendinblue/APIv3-php-library#getting-started) but can't find any other examples even for sending an simple email. Can you point me to examples or tell me how to send an email by specifying to, from, subject, and html body?

Thanks!

**Comment by stevesmithworks** [comment]
Combining bits and pieces from around the web, I think I'm supposed to do the following.

```
        $config = \SendinBlue\Client\Configuration::getDefaultConfiguration();
        $config->setApiKey('api-key', $sendinblue_api_key_v3);

        $smtpAPI = new \SendinBlue\Client\Api\SMTPApi(new \GuzzleHttp\Client(), $config);

        $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail([
            'sender' => 'support@company.com',
            'to' => 'me@gmail.com',
            'subject' => 'Sendinblue HTML Email Test',
            'htmlContent' => '<p>Hello <b>Customer</b>.</p>',
        ]);
        
        try {
            $response = $smtpAPI->sendTransacEmail($sendSmtpEmail);
            error_log($response);
        } catch (Exception $e) {
            echo 'Exception when calling SMTPApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
        }
```

**Comment by stevesmithworks** [comment]
I'm getting a 400 response from Sendinblue API with message "invalid sender". I can see in the web interface that the sender I am using is a correct email address.

**Comment by rajatsib** [comment]
Hi @stevesmithworks 
Can you share the exact response message?
