### ISSUE TITLE
Guzzlehttp v7

### ISSUE THREAD

**Issue by ojomasta** [sendinblue/APIv3-php-library#122]
I use the api of microsoft which requires guzzlehttp ^7
I see that sendinblue requires guzzlehttp ^6.2 
the sendinblue api would not work properly with version 7?

**Comment by NickBelhomme** [comment]
We are in need of this as well. We are using Laravel and want to upgrade from 7 to 8. 
For this to work we need to upgrade to guzzlehttp ^ 7.0.1 and sendinblue cannot handle this.
https://laravel.com/docs/8.x/upgrade#updating-dependencies

As Laravel is one of the biggest players in the PHP community this looks like a critical patch is needed.

**Comment by NickBelhomme** [comment]
Pull request open: https://github.com/sendinblue/APIv3-php-library/pull/116

**Comment by rajatsib** [comment]
Hi @ojomasta and @NickBelhomme 
We have merged this [PR](https://github.com/sendinblue/APIv3-php-library/pull/116) to allow guzzle 7

**Comment by NickBelhomme** [comment]
thx for the release https://github.com/sendinblue/APIv3-php-library/releases/tag/v7.1.0
