### ISSUE TITLE
Campaign // Plain-text content

### ISSUE THREAD

**Issue by glafarge** [sendinblue/APIv3-php-library#123]
We can set `htmlContent` for a campaign, however the `plainTextContent` property is not available and seems to be genereated automatically when the campaign is sent.

For specific uses cases like content with tables it would be nice to have an option to set it manually (plaintext ascii tables are beautiful ^^). 

SendSmtpEmail implement it, why not the Campaign API ?

**Comment by rajatsib** [comment]
Hi @glafarge 

Currently plaintext content property is not available for campaigns.
We will update our [changelog](https://developers.sendinblue.com/changelog) if it is supported in future
