### ISSUE TITLE
sendTemplate deprecated?

### ISSUE THREAD

**Issue by ultienne** [sendinblue/APIv3-php-library#127]
Hi,

The documentation in this repository states the `sendTemplate` functionality and/or the underlying api-route is deprecated. To be specific: `This endpoint is deprecated. Prefer v3/smtp/email instead.`

See: https://github.com/sendinblue/APIv3-php-library/blob/fb07e16f16e251b1623ae029aeea75231c12217f/docs/Api/TransactionalEmailsApi.md#sendtemplate

However, the documentation on the website states no such thing: https://developers.sendinblue.com/docs/send-a-transactional-email

Could you clarify this or remove the deprecation notice? Thanks.

**Comment by rajatsib** [comment]
Hi @ultienne 

The endpoint [sendTemplate](https://developers.sendinblue.com/reference#sendtemplate-1) is deprecated.
We recommend that you use [send a transactional email ](https://developers.sendinblue.com/reference#sendtransacemail)endpoint.

Thanks

**Comment by ultienne** [comment]
Hi,

I'm not concerned with any endpoints, I'm using the functionality the SDK is providing me with. 

Since the SDK is an abstraction on top of the API, a user of a SDK shouldn't be confronted with a "deprecated endpoint" notice somewhere on a function. Especially not without pointing to the non-deprecated alternative.

I found out the hard way I should use the `sendTransacEmail`-function. 

Mentioning that the underlying endpoint for the `sendTemplate`-function is deprecated and with it **implying** the `sendTemplate`-function is deprecated is confusing and a strange decision in a SDK. The `sendTemplate`-function should either be explicitly deprecated and point to an alternate function or it should just use the alternate function internally.

**Comment by rajatsib** [comment]
Hi @ultienne 

Thanks for pointing this out. We will mention the SDK function to use as an alternative to sendTemplate instead of the endpoint.
