### ISSUE TITLE
How do I create contacts & tasks in CRM using the API?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [sendinblue/APIv3-php-library#128]

**Comment by rajatsib** [comment]
Hi @abishekrsrikaanth 

Can you please raise a support ticket to Sendinblue for the same?

**Comment by abishekrsrikaanth** [comment]
@rajatsib, do I need to do this from within the sendinblue website?

**Comment by mourraille** [comment]
Hello @abishekrsrikaanth , it's not possible yet to hace this actions done through the API. But we will take your feedback to evaluate how could we bring this functionality. Thanks a lot.
