### ISSUE TITLE
Allow Reference Headers to emails, in order to make Email Threads for consumers.

### ISSUE THREAD

**Issue by alexanderkraemer** [sendinblue/APIv3-php-library#129]
The presence of In-Reply-To and References headers indicate that the message is a reply to a previous message. The References header makes "threaded mail reading" and per-discussion archival possible. 

It would be of great value, if this could be supported by sendinblue!

**Comment by rajatsib** [comment]
Hi @alexanderkraemer 

Can you please raise a support ticket to Sendinblue for the same?

**Comment by centricsapp** [comment]
I already did.
Thought, if that get's attention from others that would like to have that feature here as well, it might get prioritized...

**Comment by alexanderkraemer** [comment]
I already did.
Thought, if that get's attention from others that would like to have that feature here as well, it might get prioritized...
