### ISSUE TITLE
401 while sending transactional e-mail

### ISSUE THREAD

**Issue by dakorpar** [sendinblue/APIv3-php-library#13]
Hi, I'm using code from your demo:

		Configuration::getDefaultConfiguration()->setApiKey('api-key', $apiKey);
		$api_instance = new SMTPApi();
		$message = new SendSmtpEmail();
		$message->setTextContent("Blabla test");

		$message->setTo('...');
		$message->setSender('..');
		$api_instance->sendTransacEmail($message);

api key is set correctly, to and sender is same address, with which I'm registered...

**Comment by dakorpar** [comment]
ok, I've used api v2 key, not v3, I got this, but now different error:
code => "missing_parameter"
message => "email is missing in to"

		Configuration::getDefaultConfiguration()->setApiKey('api-key', $apiKey);
		$api_instance = new SMTPApi();

		$message = new SendSmtpEmail();
		$message->setTextContent("Blabla test");
		$message->setHtmlContent("Blabla test");
		$message->setSubject("test");

		$to = new SendSmtpEmailTo(['name' => 'name', 'email' => 'correct-email']);
		$message->setTo($to);```


		$sender = new SendSmtpEmailSender();
		$sender->setEmail('correct-email')->setName("name");
		$message->setSender($sender);

		if(!$message->valid()){
			print_r($message->listInvalidProperties());die;
		}
		$api_instance->sendTransacEmail($message);
```

**Comment by antoine-nedelec** [comment]
Did you find the problem ?

**Comment by dakorpar** [comment]
I don't remember anymore :)

**Comment by COil** [comment]
The "to" parameter with be passed as an array.
