### ISSUE TITLE
_toString() must return a string value  

### ISSUE THREAD

**Issue by DevZaX** [sendinblue/APIv3-php-library#133]
my code is   : 
        
 public function createEmailCampaign($post,$listIds)
    {
        $htmlContent = (new PostCreated( $post ) )->render();
        $config = \SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', env("SENDINBLUE_KEY"));
        $apiInstance = new \SendinBlue\Client\Api\EmailCampaignsApi(null,$config);
        $emailCampaigns = new \SendinBlue\Client\Model\CreateEmailCampaign();
        $emailCampaigns['sender'] =  array('name' => 'xxx', 'email' => 'xxx@gmail.com');
        $emailCampaigns['name'] = 'Campaign '.$post->id;
        $emailCampaigns['subject'] = $post->subject;
        $emailCampaigns['recipients'] = ["listIds"=>$listIds];
        $emailCampaigns['type'] = 'classic';
        $emailCampaigns["htmlContent"] = $htmlContent; 
        try{
             $result = $apiInstance->createEmailCampaign($emailCampaigns);
             echo $result->id;
             return $result->id;
        }catch(\Exception $e)
        {
            echo 'Exception when calling EmailCampaignsApi->createEmailCampaign: ', $e->getMessage(), PHP_EOL;
        }
    }

i get 

 Method SendinBlue\Client\Model\CreateEmailCampaign::__toString() must return a string value

  at vendor/guzzlehttp/psr7/src/Utils.php:323
    319▕                         $resource->next();
    320▕                         return $result;
    321▕                     }, $options);
    322▕                 } elseif (method_exists($resource, '__toString')) {
  ➜ 323▕                     return Utils::streamFor( (string)$resource, $options);
    324▕                 }
    325▕                 break;
    326▕             case 'NULL':
    327▕                 return new Stream(fopen('php://temp', 'r+'), $options);

      +4 vendor frames
  5   app/Console/Commands/SendEmails.php:50
      SendinBlue\Client\Api\EmailCampaignsApi::createEmailCampaign()

  6   app/Console/Commands/SendEmails.php:81
      App\Console\Commands\SendEmails::createEmailCampaign()

do you have any idea ?

**Comment by rajatsib** [comment]
Hi @DevZaX 

Can you try this using the latest version of PHP library ?

**Comment by rajatsib** [comment]
I am closing this issue as it could not be generated with the latest version of PHP SDK
