### ISSUE TITLE
sendinblue / APIv3-php-library create bulk contact into list

### ISSUE THREAD

**Issue by bhautikvirani** [sendinblue/APIv3-php-library#134]
Took the example code from the doc. Tried to add email as follows:

$contactEmails = new \SendinBlue\Client\Model\AddContactToList(); 

$contactEmails['emails'] = array('example@gmail.com');

$result = $apiInstance->addContactToList($listId, $contactEmails);
But, this always throws an error :

{
"code":"invalid_parameter"
"message":"Contact already in list and/or does not exist"
}

The contact is not added at all and is not present in the list. I tried with valid emails as well.

**Comment by rajatsib** [comment]
Hi @bhautikvirani 

This error usually comes when either the contact does not exist or it is already present in the specified list.
The contact should exist in the first place

You can create an ticket to Sendinblue if you still face this issue.
