### ISSUE TITLE
Time Out on contacts/import

### ISSUE THREAD

**Issue by cedric-r-mycelium** [sendinblue/APIv3-php-library#136]
On 4 january i have error 500
Now I have many [524] Server error: `POST https://api.sendinblue.com/v3/contacts/import` resulted in a `524 Origin Time-out

**Comment by rajatsib** [comment]
Hi @cedric-r-mycelium 

This could have been an intermittent issue at that time. Are you still receiving it ?

**Comment by cedric-r-mycelium** [comment]
Hi @rajatsib  

Always yes

For information : 
- The last time is the 8 april 2021 - From 17:26 To 18:09 - 36 times
- For the 7 april - From 11:57 To 12:00 - 17 times
- For the 6 april - From 8:06 To 08:08 - 2 times
- 31 march - 2 times
- 30 march - 21 times
- 29 march - 6 times
- 26 march - 25 times
- 22 march - 3 times

**Comment by rajatsib** [comment]
Hi @cedric-r-mycelium 

Kindly raise a support Ticket to Sendinblue for this. 
I am closing this issue as this is not related to the PHP SDK

Thanks
