### ISSUE TITLE
how can send batch in one api request

### ISSUE THREAD

**Issue by vahidalvandi** [sendinblue/APIv3-php-library#137]
hello , i need send batch email in one api request , sample : i have 1000 email with same text body ,

**Comment by rajatsib** [comment]
Hi @vahidalvandi 

Do you mean you need to send the same email to 1000 different email ids. Is that correct?

**Comment by webactor724** [comment]
@rajatsib  yes, i have a list of emails with same content

**Comment by rajatsib** [comment]
Hi @webactor724 @vahidalvandi

You can pass upto 99 emails in the "to" field in a single request. You can make multiple requests like these for 1000 emails.
