### ISSUE TITLE
Symfony API connect

### ISSUE THREAD

**Issue by LeZellus** [sendinblue/APIv3-php-library#141]
Hi, actually I'm trying to add your API in my application to manage credits.

After following your tutoriel , I'm actually stuck.

First I've done this : 
`composer require sendinblue/api-v3-sdk "7.x.x"`

After , I've added the code to manage configuration for secret key API in my method.

`$config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR_API_KEY');`

But the following code give me this error :

<img width="1035" alt="Capture d’écran 2021-01-28 à 10 03 24" src="https://user-images.githubusercontent.com/30074015/106114736-31759700-6150-11eb-89bc-928b73df46af.png">

I think SendinBlue API autoload doesn't work , and I don't know why `$config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR_API_KEY');` return this error message. I don't found any solution on the web.

NB : same issue with the true value for `YOUR-API-KEY`.

I need debug ASAP , thanks.

Best regards

**Comment by MDev22** [comment]
Insert on top
`use SendinBlue\Client\Configuration`
and then:
`$config = Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR_API_KEY');`

**Comment by rajatsib** [comment]
Hi @LeZellus 

Were you able to resolve the above error using [this](https://github.com/sendinblue/APIv3-php-library/issues/141#issuecomment-769927057) ?

**Comment by LeZellus** [comment]
> Hi @LeZellus
> 
> Were you able to resolve the above error using [this](https://github.com/sendinblue/APIv3-php-library/issues/141#issuecomment-769927057) ?

Yes , but Idk how to close this post

**Comment by LeZellus** [comment]
> Hi @LeZellus
> 
> Were you able to resolve the above error using [this](https://github.com/sendinblue/APIv3-php-library/issues/141#issuecomment-769927057) ?

It works
