### ISSUE TITLE
Delete Campaign - how to

### ISSUE THREAD

**Issue by MDev22** [sendinblue/APIv3-php-library#142]
After create a campaign with status "sent" and a future scheduledAt field, I want do the choose to delete the campaign.
If I change status from "sent" to "suspended" before to execute "deleteEmailCampaign", I don't receive any response.

In API Reference, I see that it's possibile delete only draft campaign.
Why I can't change status from "suspended" to "draft"? Or remove a suspendend campaign directly?

**Comment by rajatsib** [comment]
Hi @MDev22 

It is possible to delete only draft campaign.
A suspended campaign can only be moved to archived status
