### ISSUE TITLE
SendSmtpEmail - Always cast getters result as array<int, array>

### ISSUE THREAD

**Issue by DaedalusDev** [sendinblue/APIv3-php-library#145]
Hello,

i suggest to ajust ths following `SendSmtpEmail`'s methods to prevent an issue i encontered in my project.

I've use an `array_map` function on an array and unfortunaly, in older version of PHP, this will produce and unwanted result :
```php
$to = ['test@test.com', 'test2@test.com'];
$sibTo = array_map(
                static function ($email) {
                    return new SendSmtpEmailTo(['email' => $email]);
                },
                $to
             ); // result : [ "0" => 'test@test.com', "1" => 'test2@test.com' ]
```

Unfortunaly, the previous exemple will result the following json:
```json
{
  "0": "test@test.com",
  "1": "test2@test.com"
}
```
Expected json :
```json
[
  "test@test.com",
  "test2@test.com"
]
```

This is not a "bug", but this can append by inadvertence.

Thanks.

**Comment by rajatsib** [comment]
Hi @DaedalusDev 

Which version of PHP are you using ?

sendSmtpEmailTo is expected to return an array of objects rather than a plain array

**Comment by rajatsib** [comment]
I am closing it since there was no reply in last 13 days
