### ISSUE TITLE
PHP 7.4 Support - Deprecated: Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by hejazee** [sendinblue/APIv3-php-library#147]
When using php 7.4, the following warning is shown:
Deprecated: Cannot use "parent" when current class scope has no parent in api-v3-sdk/lib/Model/GetChildDomains.php on line 189

This library should be updated for PHP 7.4 (and maybe PHP 8 ...)

**Comment by rajatsib** [comment]
Hi @hejazee 

Can you share some code snippet or script which is generating this ?

**Comment by LoicLEMEUT** [comment]
Hello @rajatsib ,

I'm the Drupal developper of SendinBlue module.

We have a similar issue on Drupal become of PHP SDK, here: https://github.com/sendinblue/APIv3-php-library/blob/master/lib/Model/GetChildDomains.php#L189

You actually use a parent class, but current class ... has no parent
`Deprecated: Cannot use "parent" when current class scope has no parent in lib/api-v3-sdk/lib/Model/GetChildDomains.php on line 189`

I think you juste have to remove this line, like other Model :)

Thanks ! :) 

Loïc

**Comment by LoicLEMEUT** [comment]
Up!

**Comment by rajatsib** [comment]
Hi @LoicLEMEUT 

We are doing some changes on our side.
Will update you once done

**Comment by capuderg** [comment]
We are using this library in WP Mail SMTP plugin and a user shared that their hosting provided a list of PHP 8 compatibility issues and a few of those came from this library:

> "Using "parent" inside a class without parent is deprecated since PHP 7.4 Line 189 Type ERROR"

`.../html/wp-content/plugins/wp-mail-smtp/vendor_prefixed/sendinblue/api-v3-sdk/lib/Model/GetStatsByDomain.php`

I can see that this line is using the `parent` keyword: `$invalidProperties = parent::listInvalidProperties();` even though this class does not extend any parent classes...

They also said this error is reported in a few places in the library.

Could you please look into this and fix those PHP 8 issues?

**Comment by alf-ecedi** [comment]
Up!

**Comment by johndodev** [comment]
Up. The library should not be installable in a php 8 plateform with this 500 error.

**Comment by brigon-clever-age** [comment]
Hi everyone,

I pushed a pull request that fixes in a very "naive" way the deprecation we get from classes calling parent:: without parent class.

Hope this helps !
Best regards,
Bastien

**Comment by brigon-clever-age** [comment]
Hi again,
Since I can't create a pull request to a 7.x branch (it doesn't exist), I post a patch attached here (as .txt since I can't upload it as .patch) to allow using it on v7.4.5 tag for example.
[sendinblue-v7.4.5-php8.txt](https://github.com/sendinblue/APIv3-php-library/files/10689361/sendinblue-v7.4.5-php8.txt)

Best regards,
Bastien

**Comment by preetishishodia7** [comment]
Hi Everyone!
We have fixed this issue in our new [brevo-php](https://github.com/getbrevo/brevo-php) SDK for brevo.com domain [here](https://packagist.org/packages/getbrevo/brevo-php), you can explore and use it. If you still face any issue please let us know we will look into it.
Thanks!
