### ISSUE TITLE
Guzzle with Middleware::log 

### ISSUE THREAD

**Issue by Ark4ne** [sendinblue/APIv3-php-library#148]
Use guzzle with log middleware makes api work wrong : 

```php
$handlerStack = HandlerStack::create(new CurlHandler);

$handlerStack->push(GuzzleHttp\Middleware::log(
    new Logger('guzzle-debug'),
    new MessageFormatter(MessageFormatter::DEBUG)
));

$httpClient = new GuzzleHttp\Client([
    'handler' => $handlerStack,
]);

$email = (new SendSmtpEmail())
    ->setSender(new SendSmtpEmailSender([
        'email' => $fromEmail,
        'name' => $fromName,
    ]))
    ->setTo([new SendSmtpEmailTo([
        'email' => $toEmail
    ])])
    ->setSubject($subject)
    ->setHtmlContent($content);

$transactionalApi = (new TransactionalEmailsApi($httpClient, ...));

$response =  $transactionalApi->sendTransacEmail($email);

$response === null; // instead of CreateSmtpEmail
```

According to issue https://github.com/guzzle/guzzle/issues/2863#issuecomment-792247910, all contents retrieve from guzzle response must be get by `_toString` method.

**Comment by rajatsib** [comment]
Hi @Ark4ne 

Which logger library you are using in the statement `new Logger('guzzle-debug')` ? 
Or have you written your custom logger ?

**Comment by rajatsib** [comment]
Hi @Ark4ne 

You have to rewind the response with creating a new middleware
`$mapResponse = Middleware::mapResponse( function(ResponseInterface $response) { $response->getBody()->rewind(); return $response; } );`

And add it to the stack
`$handlerStack->push($mapResponse);`
