### ISSUE TITLE
Contact email update fail

### ISSUE THREAD

**Issue by ewennedelec** [sendinblue/APIv3-php-library#149]
I am trying to update an existing contact.

Everything goes well for all attribute except EMAIL.
A soon as I add EMAIL within the attributes to update, I get the following error message : 
{"code":"invalid_parameter","message":"Contact already exist"}

I followed your API doc [https://developers.sendinblue.com/reference#updatecontact](url) which does mention anything special. I tried the same code with your API Try it button and it works.

Is there a specific process to follow to update the email of an existing user?

Thanks in advance for you quick feedback

**Comment by ewennedelec** [comment]
It seems that your API does not support overriding the contact "EMAIL" attribute with the same value as already existing. It's OK when values are different but if values are equal, then your API returns {"code":"invalid_parameter","message":"Contact already exist"}

This behavior is really disturbing since it differs from all other attributes that can be overridden during update.

It also forces to code 2 different API calls options to update contact ... depending on EMAIL changes or not!

**Comment by rajatsib** [comment]
Hi @ewennedelec 

Please note that the 'email' parameter in attributes is used to update the contact email id with new email id.  
For example:
 If you want to update the email id: test@sendinblue.com with new email id (test_new@sendinblue.com) along with other attributes then you need to pass the following body input:
{"attributes":{"FIRSTNAME":"Shawn","LASTNAME":"Michaels","EMAIL":"test_new@sendinblue.com"}}

And if you only want to update other attributes of that contact email id then you need to pass following input body ( do not pass EMAIL parameter in attributes object): 
{"attributes":{"FIRSTNAME":"Shawn","LASTNAME":"Michaels","EMAIL":" "}}
Or 
{"attributes":{"FIRSTNAME":"Shawn","LASTNAME":"Michaels"}}

Hope I was able to clarify

Thanks

**Comment by ewennedelec** [comment]
Hi Rajatsib,

Thanks for your comment. That's the conclusion I went to after several tests.
From an API user point of view, it still remains very disturbing not to be allowed to pass the EMAIL parameter when the EMAIL does not change. It's very hard to understand why you cannot just override the previous EMAIL value with the same one in this case?

Best

Ewen

**Comment by rajatsib** [comment]
Hi Ewen

The email attribute is designed only for the purpose if user wants to update the existing email to a new one.
We will update this in our API reference soon.

Thanks

**Comment by amureki** [comment]
> Hi Ewen
> 
> The email attribute is designed only for the purpose if user wants to update the existing email to a new one. We will update this in our API reference soon.
> 
> Thanks


Greetings @rajatsib 

We stumbled upon the same issue, and it took us some time to understand where the roots are (since we are not using this PHP wrapper, but a Python one).

Is it possible to update API docs to mention this behaviour?
Thank you very much!

Best,
Rust
