### ISSUE TITLE
Uncaught Error: Class 'SendinBlue\Client\Configuration' not found in *.php

### ISSUE THREAD

**Issue by ppriyadarshini123** [sendinblue/APIv3-php-library#150]
Hi,

I have followed the instructions here: https://github.com/sendinblue/APIv3-php-library   in setting up in sending the Transactional email using SendinBlue. I keep getting this error: Uncaught Error: Class 'SendinBlue\Client\Configuration' not found in *.php. Am I missing something? 

Please help. Thanks

**Comment by rajatsib** [comment]
Hi @ppriyadarshini123 

Closing this issue due to no reply.

**Comment by boctulus** [comment]
Same problem here!

**Comment by gdesiganax** [comment]
Download the package from the composer
composer require sendinblue/api-v3-sdk "8.x.x"

**Comment by Ario92** [comment]
same problem

**Comment by Ario92** [comment]
> Download the package from the composer composer require sendinblue/api-v3-sdk "8.x.x"

I do that but the problem exists.
