### ISSUE TITLE
Documentation is wrong for the UpdateContact model

### ISSUE THREAD

**Issue by juanparati** [sendinblue/APIv3-php-library#152]
The [UpdateContact](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Model/UpdateContact.md) documentation say:

 _To update existing email address of a contact with the new one please pass EMAIL in attribtes. For example, `{ "EMAIL":"newemail@domain.com", "FNAME":"Ellie", "LNAME":"Roger"}_

I observed that when the EMAIL is passed into the attributes a 400 error is received, however when is missing it works.

I had the same issue with the CreateContact some time ago, but at least the documentation is correct for the CrecateContact model.

It also doesn't have sense to mention that EMAIL is required in the attributes because the e-mail of the customer is the first parameter of the "updateContact" method signature.

**Comment by rajatsib** [comment]
Hi @juanparati 

The API returns 400 if the email you are passing in the attributes object is already assigned to another contact or even the same contact. When you pass a new email in attributes, it should not be assigned to any contact (including the one that is being updated).
Let me know if you still face any issues.

Thanks
