### ISSUE TITLE
Method Illuminate\Support\Collection::swaggerFormats does not exist

### ISSUE THREAD

**Issue by worldtok** [sendinblue/APIv3-php-library#153]
When using this package in a laravel project added using composer, I got this message

Method Illuminate\Support\Collection::swaggerFormats does not exist. 

This happens when trying to call the ContactsApi, when creating contact using the API method

**Comment by rajatsib** [comment]
Hi @worldtok 

I tried to create contact using  PHP SDK in a laravel project and it worked for me ?
Are you using any alias for the SDK.
Can you share some information like the version and maybe a code snippet ?

**Comment by rajatsib** [comment]
Closing this issue due to no reply
