### ISSUE TITLE
Getting contact by phone number ?

### ISSUE THREAD

**Issue by Alexandre57370** [sendinblue/APIv3-php-library#155]
Hi everyone,

I would like to get a contact by phone number only (SMS attribute), how can I do that ?

Thank's a lot !

**Comment by rajatsib** [comment]
Hi @Alexandre57370 

You can pass the following in request body

{ "attributes": {"SMS": "user phone number"}}

**Comment by Alexandre57370** [comment]
> Hi @Alexandre57370
> 
> You can pass the following in request body
> 
> { "attributes": {"SMS": "user phone number"}}

Thank's ! 👍
