### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query() 

### ISSUE THREAD

**Issue by ambercouch** [sendinblue/APIv3-php-library#156]
With versions v7.1.0 to v7.4.0 I'm getting the following error after running the  "Getting Started" Code in the readme
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()

I'm using Homestead which is nginx running php 7.4 also got the same error on scotchbox running apache php 7.2

I think it looks like build_query() was deprecated .

APIv3-php-library v7.0.0 is working fine so will stick with that for now

**Comment by Maxxx42** [comment]
I have exactly the same problem !

**Comment by twyneed** [comment]
+ 1
as @ambercouch recommended. 
`"sendinblue/api-v3-sdk":"v7.0.0"` solves the issue "so far".

**Comment by rajatsib** [comment]
Hi @ambercouch @Maxxx42 @twyneed 

Thanks for reporting this issue
We have released a patch for this issue . Please use the latest version (v7.4.2) of the PHP SDK. 

Regards 
Sendinblue Team
