### ISSUE TITLE
Error with getAttributes()

### ISSUE THREAD

**Issue by defro** [sendinblue/APIv3-php-library#16]
Hello,

When I request all attributes, I got this error : `[400] Error connecting to the API (https://api.sendinblue.com/v3/contacts/attributes)`

I don't find this method in your API documentation.

Regards,
Joël

**Comment by ekta-slit** [comment]
Hi @defro 

Few endpoints are not yet implemented and this is one of them, we are working on it.
For more information please refer `Missing features` here https://developers.sendinblue.com/docs

Thanks
