### ISSUE TITLE
Retrieve Quota for transactional emails

### ISSUE THREAD

**Issue by DLO33** [sendinblue/APIv3-php-library#161]
A good feature would to be able to retrieve the current transactional email quote in the accounts API.

This would allow applications to control the amount of emails sent within the hour.

As per the sendinblue dashboard

> Transactional emails are sent with an initial limit of 40 per hour. This limit will be either raised or lowered according to the stats results and the quantity of emails sent.

**Comment by rajatsib** [comment]
Hi @DLO33 

This is a feature required at the platform level and not something which can be just exposed via the wrapper. 
Kindly raise a request to the Customer Success team

Thanks
