### ISSUE TITLE
PHP 8 and Guzzle 7.4 is not compatible with your latest version 7.4.3

### ISSUE THREAD

**Issue by bastiendonjon** [sendinblue/APIv3-php-library#164]
We have many errors like : "Call to undefined function GuzzleHttp\\Psr7\\build_query()"

Is not possible to downgrade version with latest Laravel project...

We can no longer use sendinblue in new projects.

Thanks

**Comment by bastiendonjon** [comment]
GuzzleHttp\\Psr7\\build_query() is remove since guzzle 7.2

**Comment by bastiendonjon** [comment]
Pull request to fix this #165 

You can publish new version please ?

**Comment by neoteknic** [comment]
+1 Please fix :)

**Comment by rajatsib** [comment]
PR merged to fix the issue 
Thanks @bastiendonjon for the PR
