### ISSUE TITLE
All my request result in empty object if no errors.

### ISSUE THREAD

**Issue by pantharius** [sendinblue/APIv3-php-library#166]
Hello,

I used correctly this library to send transactionnal SMS and Emails. But i have no results unless there is an error but for both calls it's not a problem.
But now, i want to create a backoffice in my website to select the template to use at each kind of call.
I tried to ask **getSmtpTemplates** but it answer `{}` every times.

My code :
```php
public static function getSmtpTemplates()
{
    $config = \SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', getenv("SENDINBLUE_API_KEY"));

    $apiInstance = new \SendinBlue\Client\Api\TransactionalEmailsApi(
        (getenv("ISDEV") == 0) ? new \GuzzleHttp\Client([
            'verify' => false
        ]) : new \GuzzleHttp\Client(),
        $config
    );

    try {
        return $apiInstance->getSmtpTemplates();
    } catch (\Exception $e) {
        return array('Exception when calling TransactionalEmailsApi->getSmtpTemplates: ', $e->getMessage(), PHP_EOL);
    }
}
```

Is something i did wrong ?
Am I asking the good service to access the list of this : 
![image](https://user-images.githubusercontent.com/81244508/129463055-84b90a60-a890-411e-8ad9-a35036e94e59.png)

i'd look on the page on xhr calls if there is something to help me but the request that return them is called at this url : https://my.sendinblue.com/campaign/campaignlistings, meaning it's a campaign email list ?

Thanks in advance,
Best Regards,

**Comment by rajatsib** [comment]
Hi @pantharius 

Please pass the templateStatus to getSmtpTemplate function like 
 
`$apiInstance->getSmtpTemplates("true") ` to get active templates

**Comment by pantharius** [comment]
i did that :
```php
    public static function getSmtpTemplates()
    {
        $config = \SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', getenv("SENDINBLUE_API_KEY"));

        $apiInstance = new \SendinBlue\Client\Api\TransactionalEmailsApi(
            (getenv("ISDEV") == 0) ? new \GuzzleHttp\Client([
                'verify' => false
            ]) : new \GuzzleHttp\Client(),
            $config
        );

        try {
            return $apiInstance->getSmtpTemplates("true");
        } catch (\Exception $e) {
            return array('Exception when calling TransactionalEmailsApi->getSmtpTemplates: ', $e->getMessage(), PHP_EOL);
        }
    }
```
result : 
```json
{}
```

**Comment by pantharius** [comment]
i also verified my domain (that was not done yet) which send the request but again it's a empty object `{}`

**Comment by pantharius** [comment]
@rajatsib Up ?
I did not solve the problem by myself

**Comment by rajatsib** [comment]
Hi @pantharius 

Can you raise a ticket to Sendinblue supoort since it looks like an account specific issue ?
In general, the getSmtpTemplates function works fine.

Thanks

**Comment by rajatsib** [comment]
Hi @pantharius 

I hope that you raised or will raise this ticket to Sendinblue support
Closing this issue

Thanks
