### ISSUE TITLE
No sendTransacEmail() method at TransactionalSMSApi.php

### ISSUE THREAD

**Issue by boryn** [sendinblue/APIv3-php-library#168]
The doc https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/TransactionalEmailsApi.md#sendtransacemail says to create api instance from `new SendinBlue\Client\Api\TransactionalEmailsApi` and use `sendTransacEmail()` method. But `sendTransacEmail()` method is not available in `TransactionalEmailsApi`, it is available in `SMTPApi.php`. Please either update docs or the location of the methods.

**Comment by rajatsib** [comment]
Hi @boryn 

SmtpApi has been replaced by TransactionalEmail Api since version 7.0.0
Can you please try to use the latest version?
If you still face the issue, please share the script that you are using?

**Comment by boryn** [comment]
Hi @rajatsib! Yes, thank you! Another library I'm using is set to use the v6 branch of this library and I was looking at the default v7 docs.
