### ISSUE TITLE
Error Contact already exist with updateEnabled

### ISSUE THREAD

**Issue by danjjl** [sendinblue/APIv3-php-library#169]
A contact cannot be updated if `EMAIL` is specified in the attributes.
This happens with `updateEnabled` set to `true`

Request:

```
- headers => (array)
     - Accept => application/json
     - Content-Type => application/json; charset=utf-8
     - API-Key => XXXXXXX
- body => {
     - 'email': 'test@test.com', 
     - 'updateEnabled': true,
     - 'attributes': {'EMAIL': 'test@test.com', 'NAME': 'test'},
     - 'listIds': [15]}
```

Response:

Code 400: `code: invalid_parameter, message: Contact already exist`

---

The request without `EMAIL` in the attributes is successful.

**Comment by rajatsib** [comment]
Hi @danjjl 

Our team is working on an improvement to handle the same.
Will keep you posted

Thanks

**Comment by rajatsib** [comment]
Hi @danjjl 

The improvement has been deployed by the team.
You should not face this issue anymore
