### ISSUE TITLE
Error with getEmailCampaigns

### ISSUE THREAD

**Issue by defro** [sendinblue/APIv3-php-library#17]
Hello,

I've got this error when a request getEmailCampaigns : `[404] Error connecting to the API (https://api.sendinblue.com/v3/emailCampaigns?limit=500&offset=0)`

Regards,
Joël

**Comment by ekta-slit** [comment]
Hi @defro 

Please raise a support request here https://account.sendinblue.com/support and share with us the complete code which let you face above issue.

Thanks
