### ISSUE TITLE
Create contract store first name and last name issue

### ISSUE THREAD

**Issue by parvageshahariar** [sendinblue/APIv3-php-library#170]
You documentation has been wrong. 

In the documentation you guys put FNAME & LNAME tags but in reality the tag should be FIRSTNAME & LASTNAME. 

Please update the documentation; it's really weird when someone spending time on it.

**Comment by rajatsib** [comment]
Hi @parvageshahariar 

I am assuming you are talking in context of POST /contacts endpoint
If it is, it should match with the attribute names that you have created. If the attributes created by you are FNAME and LNAME, it will be FNAME and LNAME
