### ISSUE TITLE
Support of guzzlehttp/guzzle  7.4.*

### ISSUE THREAD

**Issue by ybert** [sendinblue/APIv3-php-library#176]
The current sendinblue/api-v3-sdk  release does not allow to use new guzzle  release.
As some new packages require this new release we can't install last sendinblue/api-v3-sdk release.

**Comment by rajatsib** [comment]
Hi @ybert @SebastianMueller87 @bastien-phi 

The SDK now supports guzzlehttp/guzzle 7.4 . Please use the latest version 7.4.5 of the PHP SDK

Thanks
