### ISSUE TITLE
What happened to release 7.4.1 ?

### ISSUE THREAD

**Issue by PierreAntoineGuillaume** [sendinblue/APIv3-php-library#180]
Hey !

What happened to release 7.4.1 ? It is not on packagist either ; but I have it locked somewhere ; is there something wrong with it ?

![image](https://user-images.githubusercontent.com/10195761/141813346-5109e540-36cd-4961-9ff7-b4d086b0f014.png)

I couldn't find any issues regarding this release; composer shows me an error on `composer update --lock`

The tag is still here though, on commit 9b217c5

**Comment by rajatsib** [comment]
Hi @PierreAntoineGuillaume 

There was an issue with v7.4.1 . Hence we removed the particular release

**Comment by PierreAntoineGuillaume** [comment]
Hey thanks a lot for your answer !
