### ISSUE TITLE
No input in body error when htmlContent contains certain unicode characters

### ISSUE THREAD

**Issue by bluefootedbobby** [sendinblue/APIv3-php-library#184]
This error can be reproduced by doing this:

    $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();    
    
    $sendSmtpEmail['subject'] = 'Test subject';
    $sendSmtpEmail['htmlContent'] = $entire_email_html;  //$entire_email_html is the unicode text below
    $sendSmtpEmail['sender'] = array('name' => 'Sender', 'email' => 'sender@domain.com');
    $sendSmtpEmail['to'] = array( array('email' => 'receiver@domain.com') );
    
    
    try {
      $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
      print_r($result);
    } catch (Exception $e) {
      echo $e->getMessage(),PHP_EOL;
    }

Error obtained:

[400] Client error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `400 Bad Request` response:
{"code":"missing_parameter","message":"No input in body"}

🍁🍁𝐔𝐬𝐞𝐝 𝐜𝐫𝐚𝐧𝐞 𝐙𝐨𝐨𝐦𝐥𝐢𝐨𝐧 𝐐𝐘𝟑𝟎𝐕 𝟐𝟎𝟏𝟎 - 𝐟𝐫𝐨𝐦 𝐇𝐨𝐧𝐠𝐤𝐨𝐧𝐠/𝐕𝐂𝐌 𝐆𝐫𝐨𝐮𝐩🍁🍁
✨𝐵𝑟𝑎𝑛𝑑: 𝑍𝑜𝑜𝑚𝑙𝑖𝑜𝑛
✨𝑀𝑜𝑑𝑒𝑙: 𝑄𝑌30𝑉
✨𝑌𝑒𝑎𝑟: 2010
✨𝐶𝑎𝑝𝑎𝑐𝑖𝑡𝑦: 30 𝑡𝑜𝑛
✨𝐻𝑜𝑜𝑘 𝐵𝑙𝑜𝑐𝑘 : 2 𝑝𝑐𝑠.
-------------------------------------------
☎️ 𝑪𝒐𝒏𝒕𝒂𝒄𝒕 𝒎𝒆 𝒇𝒐𝒓 𝒎𝒐𝒓𝒆 𝒒𝒖𝒐𝒕𝒂𝒕𝒊𝒐𝒏 𝒂𝒏𝒅 𝒅𝒆𝒕𝒂𝒊𝒍𝒔🌸
𝑾𝒉𝒂𝒕𝒔𝑨𝒑𝒑/𝑳𝑰𝑵𝑬: ＋８４ ９０６２３３３９０
_______________________________________________
VIETNAM CONSTRUCTION MACHINES DEVELOPMENT., JSC
𝐇𝐞𝐚𝐝 𝐎𝐟𝐟𝐢𝐜𝐞: 2nd Floor, Hanoi Group Building, 442 Doi Can Street, Ba Dinh District, Hanoi, Vietnam
𝐖𝐚𝐫𝐞𝐡𝐨𝐮𝐬𝐞: Dong Tru Bridge - Truong Sa Road - Dong Anh District
𝐖𝐞𝐛𝐬𝐢𝐭𝐞: [vinacoma[.]com]
B2B Sales & Rental of Construction Machines
MACHINFO: [Machinfo[.]com]

**Comment by rajatsib** [comment]
Hi @bluefootedbobby 

I tried sending an email with similar characters and the mail was sent.
Can you please share any link to the exact html file for which you got the issue?

**Comment by rajatsib** [comment]
Closing this issue due to no reply
