### ISSUE TITLE
Use of this library to send template emails from Laravel considering sendinblue is not a default email sender

### ISSUE THREAD

**Issue by usmanialiq** [sendinblue/APIv3-php-library#185]
So I have been knocking my head off to various libraries which I believe should have dispatched email from Laravel after defining something like,
`$emailPayload = [
     'templateId' => 272,
  ];
$sendEmail = new SendInBlueMail($emailPayload);
Mail::mailer('sendinblue')->to($email)->send($sendEmail);
`
But to my disappointment only, now I am using this official SDK and after installing it I am receiving this error on the line
`SendinBlue\Client\Configuration::getDefaultConfiguration()`
Note that I have imported **SendinBlue** after defining it in _app.php_

Can someone help me here, I do not want to use my default email sender!

**Comment by rajatsib** [comment]
Hi @usmanialiq 

This is a barebones PHP SDK.  Can you refer to this [comment](https://github.com/sendinblue/APIv3-php-library/issues/115#issuecomment-772951465) and check if it works for your integration as well?
