### ISSUE TITLE
Can not find getSender api

### ISSUE THREAD

**Issue by salim-hosen** [sendinblue/APIv3-php-library#189]
I want get a sender info so that i can show during update. How can i get specific Sender?

**Comment by rajatsib** [comment]
Hi @salim-hosen 

If you want to retrieve a particular contact, you can do so using the [getContactInfo](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/ContactsApi.md#getcontactinfo) method.

**Comment by salim-hosen** [comment]
Sorry, I Wrote it wrong. I want to get the specific Sender. Suppose I have a Sender list and i want to update one so when i click edit i want to get that sender so that i can show them in update form.

**Comment by rajatsib** [comment]
Hi @salim-hosen 
The [getSenders](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/SendersApi.md#getsenders) method gives you all details for all the senders. You can use the information from the senderList to update the sender
