### ISSUE TITLE
This lib requires Guzzle ! Why ? Use Interfaces and not implementations !

### ISSUE THREAD

**Issue by thalassa-web** [sendinblue/APIv3-php-library#194]
Recently I had to use the SendinBlue API in my PHP project.
What was my surprise when I saw I had to download Guzzle (via composer of course).
I already developped a small lib to comunicate with another API and I didn't force the lib user to use a specific implementation for the http calls. The user have to give an implementation of a PSR ClientInterface.
This way, the user can use whatever implementation he wants.
Furthermore, if I have to call x differents API and each lib chose a different implementation for the HTTP calls, the project downloads a lot of different projects to do the same thing …

Could you change that and offer to the users (other devs) the choice ? Whatever lib wich respect PSR-7, 17 and 18 ? 

In my PHP lib project, for exemple, I use HTTPlug (https://docs.php-http.org/en/latest/httplug/introduction.html) and I don't need to specify a specific lib.

**Comment by rajatsib** [comment]
Hi @thalassa-web 

This is an auto-generated wrapper by swagger. At the moment, we can't change it.
But the planning/discussion of a custom wrapper is in progress. 
Thank you for the valuable feedback.

Regards

**Comment by thalassa-web** [comment]
Hi @rajatsib 
I understand now !
So it may be a Swagger problem …
Is a Swagger project exist in GitHub to report the issue ?

**Comment by rajatsib** [comment]
Hi @thalassa-web 

I see that you have already raised an issue in swagger codegen. Closing this issue for now

Thanks
