### ISSUE TITLE
Lack of support for "loadedByProxy" event for SendinBlue\Client\Api\TransactionalEmailsApi->getEmailEventReport()

### ISSUE THREAD

**Issue by OlivierM68** [sendinblue/APIv3-php-library#195]
When the function SendinBlue\Client\Api\TransactionalEmailsApi->getEmailEventReport() without specifying the event parameter, there is an exception. 
The GetEmailEventReportEvents class lacks the declaration of the constant "const EVENT_LOADED_BY_PROXY = 'loadedByProxy';" at line 224. And the support for this constant in the getEventAllowableValues() function at line 233:

public function getEventAllowableValues()
     {
         return [
             self::EVENT_BOUNCES,
             self::EVENT_HARD_BOUNCES,
             self::EVENT_SOFT_BOUNCES,
             self::EVENT_DELIVERED,
             self::EVENT_SPAM,
             self::EVENT_REQUESTS,
             self::EVENT_OPENED,
             self::EVENT_CLICKS,
             self::EVENT_INVALID,
             self::EVENT_DEFERRED,
             self::EVENT_BLOCKED,
             self::EVENT_UNSUBSCRIBED,
             self::EVENT_ERROR,
             self::EVENT_LOADED_BY_PROXY /* new constant */
         ];
     }

**Comment by rajatsib** [comment]
Hi @OlivierM68 

Please install the latest version of the SDK (8.1.0) which handles the loadedByProxy event

Thanks
