### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by gmeister2** [sendinblue/APIv3-php-library#196]
When will there be support for PHP 8.1?

I encountered problems with the implementation of ArrayAccess (https://www.php.net/manual/en/class.arrayaccess.php), which is used in multiple files (sendinblue/api-v3-sdk/lib/Model).

This article describes the deprecation notices and also the solutions:
https://php.watch/versions/8.1/internal-method-return-types

**Comment by RedskyThirty** [comment]
Same for me.
I just updated to the release 8.0.0 but I still have the same error.

**Comment by rajatsib** [comment]
Hi @gmeister2 

This is an auto-generated wrapper by swagger. At the moment, we can't change it.
But the planning/discussion of a custom wrapper is in progress.
Thank you for the valuable feedback.

Regards

**Comment by M4SX5** [comment]
Hi @rajatsib 

Why is this issue closed? The problem is still there. I just updated to version 8.1.3 and the error still occurs. 
Will there be support for PHP 8.1?

Thanks for your help.

**Comment by nerv-patolog** [comment]
> Hi @rajatsib
> 
> Why is this issue closed? The problem is still there. I just updated to version 8.1.3 and the error still occurs. Will there be support for PHP 8.1?
> 
> Thanks for your help.

Agree, the issue still exists

**Comment by nerv-patolog** [comment]
Btw, the fix is pretty simple: just to add a return type to 3 methods:

```
offsetExists
offsetSet
offsetUnset
```
I've done it manually for the time being, until the library fix done

**Comment by hyde1** [comment]
> Hi @gmeister2
> 
> This is an auto-generated wrapper by swagger. At the moment, we can't change it. But the planning/discussion of a custom wrapper is in progress. Thank you for the valuable feedback.
> 
> Regards

Hi,

This issue has been fixed in swagger-codegen: https://github.com/swagger-api/swagger-codegen/pull/11846
Do you plan to update this repo to allow php 8.x compatibility?

Best,

**Comment by BafS** [comment]
It has been fixed but no new release was create so it's not on packagist yet unfortunately

**Comment by dunebaud** [comment]
Do you have a roadmap for the 8.1 compatibility?
