### ISSUE TITLE
OPcache compiling error with sendinblue/api-v3-sdk/lib/Model/AbTestVersionClicks.php

### ISSUE THREAD

**Issue by franck-grenier** [sendinblue/APIv3-php-library#197]
Hello SendinBlue,
I'm using your SDK on a Laravel 8.83.0 and I get an error when compiling my OPCache scripts with your script `lib/Model/AbTestVersionClicks.php` : 

```
[2022-03-01 18:03:01] tst.ERROR: Cannot use "parent" when current class scope has no parent {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use \"parent\" when current class scope has no parent at /home/releases/171/vendor/sendinblue/api-v3-sdk/lib/Model/AbTestVersionClicks.php:190)
```

Your class `AbTestVersionClicks` has no parent implementation of `listInvalidProperties()`. Then the call `$invalidProperties = parent::listInvalidProperties();` throws a fatal error.

I'm trying to blacklist this file to avoid OPCache compiling it.

It would be great to have a fix !

Thanks

**Comment by Mahima-eng** [comment]
hi @franck-grenier ,

We will look into it shortly and share an update soon.

**Comment by franck-grenier** [comment]
Hello,
great if you can work on it.

Waiting for a fix, I simply excluded your lib from Opcache compilation in my Laravel app: 

```php
<?php

return [
    'url' => env('OPCACHE_URL', config('app.url')),
    'prefix' => 'opcache-api',
    'verify' => true,
    'headers' => [],
    'directories' => [
        base_path('app'),
        base_path('bootstrap'),
        base_path('public'),
        base_path('resources'),
        base_path('routes'),
        base_path('storage'),
        base_path('vendor'),
    ],
    'exclude' => [
        'test',
        'Test',
        'tests',
        'Tests',
        'stub',
        'Stub',
        'stubs',
        'Stubs',
        'dumper',
        'Dumper',
        'Autoload',
        'sendinblue/api-v3-sdk' // does not compile well...
    ],
];
```

**Comment by preetishishodia7** [comment]
Hi @franck-grenier 
We have fixed this issue in our new [brevo-php](https://github.com/getbrevo/brevo-php) SDK which support brevo.com domain [here](https://packagist.org/packages/getbrevo/brevo-php), you can explore and use it. If you still face any issue please let us know we will look into it.
Thanks!
