### ISSUE TITLE
"event" parameters is now required for getEmailEventReport 

### ISSUE THREAD

**Issue by juanparati** [sendinblue/APIv3-php-library#199]
It seems that API specs has been changed an the "event" parameters attribute is required.

My Sendinblue events sync job started to failed in February after of almost 1 year of uninterrupted work.

Now the following error is raised:

`InvalidArgumentException with message 'Invalid value for 'event', must be one of 'bounces', 'hardBounces', 'softBounces', 'delivered', 'spam', 'requests', 'opened', 'clicks', 'invalid', 'deferred', 'blocked', 'unsubscribed', 'error'`

According to the documentation the "event" is still optional:
https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/TransactionalEmailsApi.md#getEmailEventReport

I can understand that library developers were not aware of this change, but it could be nice that Sendinblue back-end team can notify this breaking changes on the API, so at least the client library developers can update the documentation.

**Comment by BorisValgo** [comment]
Hy,

I have the same problem, it's due to event : "loadedByProxy"

**Comment by rajatsib** [comment]
Hi @juanparati 

We have incorporated this change in the latest version of the SDK. You should not face this issue after switching to the latest version 

Thanks
