### ISSUE TITLE
SendinBlue gives "connection refused" Laravel:Guzzle

### ISSUE THREAD

**Issue by joshuahiwat** [sendinblue/APIv3-php-library#200]
$config = Configuration::getDefaultConfiguration()->setApiKey('api-key', '[secret]');
        $apiInstance = new TransactionalEmailsApi(
            new GuzzleHttp\Client([
                'base_uri' => 'https://[secret].online',
                'protocols' => ['https'],
            ]),
            $config
        );
        $sendSmtpEmail = new SendSmtpEmail();
        $sendSmtpEmail['to'] = [
            [
                'email' => $parameters['mail'],
                'name' => $parameters['user'],
            ]
        ];
        $sendSmtpEmail['templateId'] = 3;
        $sendSmtpEmail['params'] = [
            'FIRSTNAME' => $parameters['user'],
            'LASTNAME' => $parameters['verification_code'],
        ];

        try {
            $apiInstance->sendTransacEmail($sendSmtpEmail);
        } catch (TransferException $e) {
            echo 'Exception when calling TransactionalEmailsApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
        }

Error: 
```
Exception when calling TransactionalEmailsApi->sendTransacEmail: Connection refused for URI
https://api.sendinblue.com/v3/smtp/email
```

Weird because with other apis like Mailchimp there is no error. Composer is up to date. I do a ssl request so that isn't the issue.

**Comment by rajatsib** [comment]
Hi @joshuahiwat 

What is the use of base_uri in this context ?
