### ISSUE TITLE
Add Tags in SendinBlue\Client\Model\SendSmtpEmail

### ISSUE THREAD

**Issue by paxecotree** [sendinblue/APIv3-php-library#201]
### Add Tags in SendinBlue\Client\Model\SendSmtpEmail

Class SMTPApi.php
function sendTransacEmail(\SendinBlue\Client\Model\SendSmtpEmail $sendSmtpEmail)

if you use the class SendSmtpEmail in param you cant add Tags but if you use an array you can.

### Exemple

$options = [
    'to' => [['email' => 'test@test.com']],
    'subject' => 'testing tag',
    'tags' => [testing],
     ....
];

$this->SMATPApi->sendTransacEmail(new SendSmtpEmail($options)); Send email without Tags
$this->SMATPApi->sendTransacEmail($options); Send email with Tags

**Comment by rajatsib** [comment]
Hi @paxecotree 

I tried the following example and it worked irrespective of tags 

$body = new \SendinBlue\Client\Model\SendSmtpEmail(); 
$params = array('email' => 'xyz@gmail.com', 'name' => 'Jane Doe');
$body['to'] = array(
    array('email' => 'xyz@gmail.com', 'name' => 'Jane Doe')
);;
$body['subject'] = 'Smtp email wrapper test';
$body['htmlContent'] = '<html><head></head><body><h1>Hello this is Test</h1></body></html>';
$body['tags']= array('test');
$result = $apiInstance->sendTransacEmail($body);
