### ISSUE TITLE
deals

### ISSUE THREAD

**Issue by webspin** [sendinblue/APIv3-php-library#202]
Hi, 

When would i be able to CRUD deals?

**Comment by rajatsib** [comment]
Hi @webspin 

Can you please elaborate on your query a bit? Is it an endpoint you are asking ?

**Comment by webspin** [comment]
Hi,

Yes, we are using the CRM but our app creates the offers sent to the clients. We would like to be able to automatically add a deal when an offer is made, so we can view the deal/offer on the crm deals page.

**Comment by rajatsib** [comment]
Hi @webspin 

Thanks for clarifying. This is a product requirement that is not there at the moment. If endpoints for deals are built, it will be incorporated into the SDK's as well.

Regards
