### ISSUE TITLE
TransactionalEmailsApi->getEmailEventReport tags argument not accepting multiple values

### ISSUE THREAD

**Issue by adamsargant** [sendinblue/APIv3-php-library#203]
I'm trying to filter the events returned by the TransactionalEmailsApi->getEmailEventReport endpoint by multiple tags... the documentation states 

`$tags = "tags_example"; // string | Filter the report for tags (serialized and urlencoded array)`

If I serialize and urlencode the array and pass it as a string, it appears to be result in an empty array being returned every time. If I pass a single value as an array, it works fine and returns only events that contain that tag, but as soon as I add more than one value to the array, it returns an empty array again. If this is expected behaviour, and an issue with documentation I can work round it, but if it is a bug... help :-)

so

```
        ...
        $tags = isset($parameters['tags']) ? $parameters['tags'] : []; 
        $permanenttags = ['CompanyId_' . $this->companyId];
        $tags = array_merge($tags, $permanenttags) ;
       try {
            $result = $this->transactionalEmailsApi->getEmailEventReport($limit, $offset, $startDate, $endDate, $days, $email, $event, $tags, $messageId, $templateId, $sort);
            ...
```
works as long as I don't add anything into ($parameters['tags']), but 

```
        ...
        $tags = isset($parameters['tags']) ? $parameters['tags'] : []; 
        $permanenttags = ['CompanyId_' . $this->companyId];
        $tags = urlencode( serialize( array_merge($tags, $permanenttags) ) );
       try {
            $result = $this->transactionalEmailsApi->getEmailEventReport($limit, $offset, $startDate, $endDate, $days, $email, $event, $tags, $messageId, $templateId, $sort);
            ...
```
always returns nothing

**Comment by rajatsib** [comment]
Hi @adamsargant 

Can you please pass tags as a comma-separated string? It will work.

Regards

**Comment by rajatsib** [comment]
Closing this issue

Thanks
