### ISSUE TITLE
PHP 8.1.4 deprecated function

### ISSUE THREAD

**Issue by sirsquall** [sendinblue/APIv3-php-library#207]
Hi,

I have sendingblue enabled with php 8.1.4, and we have this error message:
Deprecated function : Return type of SendinBlue\Client\Model\GetAttributesAttributes::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice dans include() (./vendor/sendinblue/api-v3-sdk/lib/Model/GetAttributesAttributes.php ligne 43)

Thanks

**Comment by preetishishodia7** [comment]
Hi @sirsquall currently we don't support PHP 8.1.4. Please use PHP 7.4

**Comment by sirsquall** [comment]
It's the only error, do you know, when you will support php 8 ?

**Comment by preetishishodia7** [comment]
I think it will take time, will update you once it is done
