### ISSUE TITLE
psr-4 issue

### ISSUE THREAD

**Issue by shinnlu** [sendinblue/APIv3-php-library#208]
when i run composer update this morning, i got error
```
Generating optimized autoload files
Class SendinBlue\Client\Model\GetScheduledEmailByBatchId located in ./vendor/sendinblue/api-v3-sdk/lib/Model/GetScheduledEmailByBatchid.php does not comply with psr-4 autoloading standard. Skipping.
Class SendinBlue\Client\Model\GetScheduledEmailByMessageId located in ./vendor/sendinblue/api-v3-sdk/lib/Model/GetScheduledEmailByMessageid.php does not comply with psr-4 autoloading standard. Skipping.
Class SendinBlue\Client\Model\GetScheduledEmailByBatchIdBatches located in ./vendor/sendinblue/api-v3-sdk/lib/Model/GetScheduledEmailByBatchidBatches.php does not comply with psr-4 autoloading standard. Skipping.
```
there are case sensitive issue with 
SendinBlue\Client\Model\GetScheduledEmailByBatch`Id` GetScheduledEmailByBatch`id`.php
SendinBlue\Client\Model\GetScheduledEmailByMessage`Id` GetScheduledEmailByMessage`id`.php
SendinBlue\Client\Model\GetScheduledEmailByBatch`Id`Batches GetScheduledEmailByBatch`id`Batches.php

**Comment by preetishishodia7** [comment]
Hi @shinnlu  we have resolved this issue in our latest release. Please use latest version for PHP sdk.
