### ISSUE TITLE
Not compatible with php 8*

### ISSUE THREAD

**Issue by WebOrganics** [sendinblue/APIv3-php-library#210]
The Sendinblue php library is not compatible with PHP 8.*

Environment:
`PHP 8.1.4 (cli) (built: Mar 18 2022 09:32:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies`

Follow instructions for "create contact" in the API documentation [Create Contact](https://developers.sendinblue.com/reference/createcontact)

Returns the following errors....

`PHP Deprecated:  Return type of SendinBlue\Client\Model\GetContacts::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 273`

`Deprecated: Return type of SendinBlue\Client\Model\GetContacts::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 273`

`PHP Deprecated:  Return type of SendinBlue\Client\Model\GetContacts::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /...i/vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 285`

`Deprecated: Return type of SendinBlue\Client\Model\GetContacts::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 285`

`PHP Deprecated:  Return type of SendinBlue\Client\Model\GetContacts::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 298`

`Deprecated: Return type of SendinBlue\Client\Model\GetContacts::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 298`

`PHP Deprecated:  Return type of SendinBlue\Client\Model\GetContacts::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /..../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 314`

`Deprecated: Return type of SendinBlue\Client\Model\GetContacts::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /.../vendor/sendinblue/api-v3-sdk/lib/Model/GetContacts.php on line 314
SendinBlue\Client\Model\GetContacts Object`

Please make your SDK PHP 8.* compatible.

**Comment by preetishishodia7** [comment]
Hi @WebOrganics  currently we don't support PHP 8*. Please use PHP 7.4

**Comment by fbnfgc** [comment]
Hi @preetishishodia7, PHP 8.* in under active support since November 2020, please see https://www.php.net/supported-versions.php. 

Did you consider bumping a major version to remove PHP 5.* and introduce PHP 8.* support? :pray:

**Comment by GMalesherbes** [comment]
Any update ?
