### ISSUE TITLE
Says support for PHP 5.6+ but when I update composer, dependency guzzle requires PHP 7.2.5+

### ISSUE THREAD

**Issue by lombrozo2** [sendinblue/APIv3-php-library#211]
I installed composer for Windows using PHP 5.6. When I run composer require sendinblue/api-v3-sdk "8.x.x" I get this error:

Running composer update sendinblue/api-v3-sdk
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzlehttp/guzzle[7.4.0, ..., 7.4.2] require php ^7.2.5 || ^8.0 -> your php version (5.6.0) does not satisfy that requirement.
    - sendinblue/api-v3-sdk[v8.0.0, ..., v8.2.1] require guzzlehttp/guzzle ^7.4.0 -> satisfiable by guzzlehttp/guzzle[7.4.0, 7.4.1, 7.4.2].
    - Root composer.json requires sendinblue/api-v3-sdk 8.x.x -> satisfiable by sendinblue/api-v3-sdk[v8.0.0, v8.1.0, v8.2.0, v8.2.1].

Installation failed, deleting ./composer.json.

Is it really possible to use the library with PHP 5.6?

**Comment by preetishishodia7** [comment]
Hi @lombrozo2 Can you please try to update PHP version but keep it less than 7.4 otherwise you will face issues., it won't work.

**Comment by preetishishodia7** [comment]
Yes @tbba it doesn't support current PHP version.

**Comment by tbba** [comment]
What is the problem? The OP cache? 
(PHP 7.3 is EOL - Outdated versions of software are not legal to use in Germany, GDPR)

**Comment by GennadyK** [comment]
It does work with PHP 5.6 at least v6.0.0 and maybe some newer versions. Use:
`composer require sendinblue/api-v3-sdk "6.0.0"`
