### ISSUE TITLE
getContactInfo - incomplete DOI ?

### ISSUE THREAD

**Issue by tbba** [sendinblue/APIv3-php-library#214]
What is the best way to receive this info from getContactInfo:
- unsubscribed/deleted
- subscribed but DOI mail confirmation click missing
- subscribed and active

I receive a "not found on "subscribed but DOI mail confirmation click missing" - I would expect a "found" with some additional info about problems.

**Comment by preetishishodia7** [comment]
Hi @tbba `getcontactInfo` is running fine at our end we are able to get additional info about contact. could you please provide the payload what you are using for more clarification. Also can you please tell which version of PHP are you using. Currently we are not supporting  >7.4 PHP version , this can also be the issue in your case if you are using higher version.

**Comment by tbba** [comment]
Hello, thank you for coming back to this. I didn't expect an answer anymore and the case is now with the German SIB support. 

Basically I agree that getcontactInfo gives me a lot of information. I just couldn't figure out how to reliably get the information I want: "has registered, but DOI mail confirmation click is missing", i.e. the email is there, but not yet valid for a mailing. Your code examples didn't go that far explaining that with a working example. Our web visitors are not very computer savvy and DOI emails don't always get the attention they need.

**Comment by tbba** [comment]
Unfortunately, I received no usable help from the German support either.
How can I detect this status: "email exists but double-opt in is missing" for an email?

**Comment by preetishishodia7** [comment]
Hi @tbba currently we are supporting this feature which satisfy your use case. Will try to improve this if this will possible at our end. So we are closing this issue for now. 
Thanks!
