### ISSUE TITLE
PHP 8.1 ArrayAccess deprecation

### ISSUE THREAD

**Issue by Shitric** [sendinblue/APIv3-php-library#217]
I am getting the following error due to ArrayAccess update when using PHP 8.1.

`During inheritance of ArrayAccess: Uncaught ErrorException: Return type of SendinBlue\Client\Model\SendSmtpEmailTo::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

**Comment by hyde1** [comment]
Same deprecation error here. Do you plan to support PHP 8.1?

**Comment by D0L1K** [comment]
Same here, would be great to have support for 8.1

**Comment by preetishishodia7** [comment]
Hi @Shitric @hyde1 @D0L1K Currently we are not supporting till PHP 7.4. Will try to upgrade it to PHP 8 soon. For now please use PHP 7.4.  Thanks.

**Comment by pankshiks** [comment]
[sendinblue_api_support_php81.patch](https://github.com/sendinblue/APIv3-php-library/files/10342223/sendinblue_api_support_php81.patch)
Here is the patch to support php8.1
