### ISSUE TITLE
Many-many deprecated functions

### ISSUE THREAD

**Issue by ivose** [sendinblue/APIv3-php-library#218]
Please update your code::

Deprecated: Return type of SendinBlue\Client\Model\GetAccount::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccount.php on line 468

Deprecated: Return type of SendinBlue\Client\Model\GetAccount::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccount.php on line 480

Deprecated: Return type of SendinBlue\Client\Model\GetAccount::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccount.php on line 493

Deprecated: Return type of SendinBlue\Client\Model\GetAccount::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccount.php on line 509

Deprecated: Return type of SendinBlue\Client\Model\GetExtendedClientAddress::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetExtendedClientAddress.php on line 340

Deprecated: Return type of SendinBlue\Client\Model\GetExtendedClientAddress::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetExtendedClientAddress.php on line 352

Deprecated: Return type of SendinBlue\Client\Model\GetExtendedClientAddress::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetExtendedClientAddress.php on line 365

Deprecated: Return type of SendinBlue\Client\Model\GetExtendedClientAddress::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetExtendedClientAddress.php on line 381

Deprecated: Return type of SendinBlue\Client\Model\GetAccountPlan::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountPlan.php on line 464

Deprecated: Return type of SendinBlue\Client\Model\GetAccountPlan::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountPlan.php on line 476

Deprecated: Return type of SendinBlue\Client\Model\GetAccountPlan::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountPlan.php on line 489

Deprecated: Return type of SendinBlue\Client\Model\GetAccountPlan::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountPlan.php on line 505

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelay::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelay.php on line 274

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelay::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelay.php on line 286

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelay::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelay.php on line 299

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelay::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelay.php on line 315

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelayData::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelayData.php on line 307

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelayData::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelayData.php on line 319

Deprecated: Return type of SendinBlue\Client\Model\GetAccountRelayData::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp\htdocs\...\vendor\sendinblue\api-v3-sdk\lib\Model\GetAccountRelayData.php on line 332

**Comment by Renrhaf** [comment]
This issues are present on PHP 8.1 for me, using the 7.4.4 SDK version.

**Comment by preetishishodia7** [comment]
Hi @ivose currently we are not supporting PHP version above 7.4. that's why you are getting warning. will upgrade it soon.
