### ISSUE TITLE
Out_of_range , Limit exceeds max value issue

### ISSUE THREAD

**Issue by jaguar988** [sendinblue/APIv3-php-library#221]
When i try to get all email campaigns i get this error:
[400] Client error: `GET https://api.sendinblue.com/v3/emailCampaigns?limit=500&offset=0&sort=desc` resulted in a `400 Bad Request` response: {"code":"out_of_range","message":"Limit exceeds max value"}

everything is working properly except this one,
the paramaters of this function getEmailCampaigns() are optional i did not include them also few days ago it was working fine
but today it keeps giving me this issue also ive tried another api same error.

`        $config = \SendinBlue\Client\Configuration::getDefaultConfiguration()
        ->setApiKey('api-key', env('SENDINBLUE_API_KEY'));

        $apiInstance = new \SendinBlue\Client\Api\EmailCampaignsApi(
            new \GuzzleHttp\Client(),
            $config
        );   
        try {

            $emailCampaigns = $apiInstance->getEmailCampaigns();
            $emailCampaigns = json_decode($emailCampaigns, true);
        } catch (\Exception $e) {
		 return redirect()->back()->withErrors(['error', $e->getMessage()]);
        }`

**Comment by preetishishodia7** [comment]
Hi @jaguar988 we allowed max `limit=100`, if you pass `limit>100` it will throw this error `{"code":"out_of_range","message":"Limit exceeds max value"}`please pass value as per limit it will work fine. if you still face issue after passing value as per limit then let me know.
Thanks!
