### ISSUE TITLE
Limit

### ISSUE THREAD

**Issue by ecedi-ld** [sendinblue/APIv3-php-library#223]
Hi,

I've got an error on lib/Api/EmailCampaignsApi.php with limit set to 500 by default :

` [error]  [400] Client error: `GET https://api.sendinblue.com/v3/emailCampaigns?type=classic&limit=500&offset=0` resulted in a `400 Bad Request` response:
{"code":"out_of_range","message":"Limit exceeds max value"}`

Did you know the new max value ?

**Comment by preetishishodia7** [comment]
Hi @ecedi-ld  we allowed max limit=100, if you pass limit>100 it will throw this error {"code":"out_of_range","message":"Limit exceeds max value"}please pass value as per limit it will work fine. if you still face issue after passing value as per limit then let me know.
Thanks!

**Comment by ecedi-ld** [comment]
Hi @preetishishodia7 

Thank you for your answer but why the default value is 500 in file lib/Api/EmailCampaignsApi.php if the limit is 100 ? We didn't set this parameter when we call the function in order to use the default value.

Regards.
