### ISSUE TITLE
The changes to `getEmailCampaign` breaks (at least) the `recipients` and `statistics` fields.

### ISSUE THREAD

**Issue by tasinttttttt** [sendinblue/APIv3-php-library#225]
The changes to `getEmailCampaign` breaks (at least) the `recipients` and `statistics` fields.

Steps to reproduce:

```php
$config = Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'API-KEY');
$apiInstance = new \SendinBlue\Client\Api\EmailCampaignsApi(
  new \GuzzleHttp\Client(),
  $config
);
$campaign = $apiInstance->getEmailCampaign($id);
// results recipients having a GetSmsCampaignRecipients type with an empty content

$campaign->getRecipients(); // results in empty
```

Last working comit is 74d4b0ffb1cfc377a3744291de206122fcf5ed37

_Originally posted by @tasinttttttt in https://github.com/sendinblue/APIv3-php-library/issues/219#issuecomment-1162534760_

**Comment by preetishishodia7** [comment]
Hi @tasinttttttt We have fixed this it now. Thanks for commenting.
