### ISSUE TITLE
composer.json indicate php 8.1 compatibility

### ISSUE THREAD

**Issue by hyde1** [sendinblue/APIv3-php-library#227]
Hello,

The composer.json indicates a php 8.1 compatibility:

```json
"php": ">=5.6",
```

But the package is not compatible as mentioned by some issues like #196 and #217.
It would be great to replace that line by something like:

```json
"php": "^5.6 || ^7.0 || 8.0",
```

or

```json
"php": "5.6 - 8.0",
```

Thanks

**Comment by preetishishodia7** [comment]
Hi @hyde1, thanks for the suggestion. Will replace it soon.

**Comment by hyde1** [comment]
Hello,

The issue has been closed but it has not been fixed. Why don't you let the issue opened until it's fixed?

Thanks
