### ISSUE TITLE
ResellerApi::getChildDomains is unusable (always return empty array)

### ISSUE THREAD

**Issue by johndodev** [sendinblue/APIv3-php-library#231]
Hi,

In addition to a php 8 compatibility error referenced  in #147, 
the function will always return an empty and fresh new instance of class SendinBlue\Client\Model\GetChildDomains.

I checked the code, the guzzle response is ok, contains data. 
- The code go to ObjectSerializer::deserialize (Reseller API line 2441).
- new instance of GetChildDomains is created on ObjectSerializer line 306.
- The code make a foreach on $instance::swaggerTypes(), but GetChildDomains::swaggerTypes() will always return an empty array.

So the returned instance of GetChildDomains is never hydrated.

I understand you use a code generator, but it would be nice to fix your swagger def.

**Comment by preetishishodia7** [comment]
Hi @johndodev 
We really appreciate your findings we will look into it.
