### ISSUE TITLE
"No input in body" error message

### ISSUE THREAD

**Issue by t1m0t** [sendinblue/APIv3-php-library#232]
Hi I'm having this issue and I can't find the solution so far so I'm posting it here if someone can help.

My script is as follow:
```php
<?php

error_reporting(E_ALL);
ini_set("display_errors", 1);

require_once($_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php');

$filename = 'templates/example.html';
$file = fopen($filename, 'r');
$filesize = filesize($filename);
$content = fread($file, $filesize);

$credentials = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'dffdsfsdfsdfsdfsdfs');
$apiInstance = new SendinBlue\Client\Api\TransactionalEmailsApi(new GuzzleHttp\Client(), $credentials);
$sender = new \SendinBlue\Client\Model\SendSmtpEmailSender([
    "name" => "test",
    "email" => "test@dfdgdgdfg.fr"
]);
$to = new \SendinBlue\Client\Model\SendSmtpEmailTo(["email" => "sdsdfsdfsfsdf@gmail.com", "name" => "Timothée"]);

$sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail([
    'sender' => $sender,
    'subject' => 'from the PHP SDK!',
    'to' => array($to),
    'htmlContent' => $content,
    'params' => (object) ['bodyMessage' => 'made just for you!']
]);

try {
    $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
    print_r($result);
} catch (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
}

```

I get this error message: 
[400] Client error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `400 Bad Request` response: {"code":"missing_parameter","message":"No input in body"}

I'm stuck here, so some help would be very much appreciated.

**Comment by preetishishodia7** [comment]
Hi @t1m0t Please try to use this script it will work. Also for more information please refer this [LINK ](https://developers.sendinblue.com/reference/sendtransacemail), it has language specific examples also.
`<?php
require_once(__DIR__ . '/vendor/autoload.php');

// Configure API key authorization: api-key
$config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR API KEY');

$apiInstance = new SendinBlue\Client\Api\TransactionalEmailsApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client(),
    $config
);
$sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail(); 
$sendSmtpEmail['subject'] = 'My subject';
$sendSmtpEmail['htmlContent'] = '<html><body><h1>This is a transactional email </h1></body></html>';
$sendSmtpEmail['sender'] = array('name' => 'John Doe', 'email' => 'example@domain.com');
$sendSmtpEmail['to'] = array(
    array('email' => 'example@domain.com', 'name' => 'Jane Doe')
);
$sendSmtpEmail['templateId'] = 4;
$sendSmtpEmail['cc'] = array(
    array('email' => 'example@domain.com', 'name' => 'Janice Doe')
);
$sendSmtpEmail['bcc'] = array(
    array('email' => 'example@domain.com', 'name' => 'John Doe')
);
$sendSmtpEmail['replyTo'] = array('email' => 'replyto@domain.com', 'name' => 'John Doe');
$sendSmtpEmail['headers'] = array('Some-Custom-Name' => 'unique-id-1234');
$sendSmtpEmail['params'] = array('parameter' => 'My param value', 'subject' => 'New Subject');

try {
    $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling TransactionalEmailsApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
}
?>`

**Comment by slaFFik** [comment]
@preetishishodia7 Unfortunately, your reply wasn't helpful at all.
The issue is not about sending an email (and you just copy-pasted the docs here), but rather about the specific error: 
```
{"code":"missing_parameter","message":"No input in body"}
```
This is not covered by docs. And this response is clearly misleading because there is a content in the email.
