### ISSUE TITLE
Obsolete limit for getEmailEventReport()

### ISSUE THREAD

**Issue by sylfabre** [sendinblue/APIv3-php-library#236]
According to your doc, we can now fetch up to 2500 events from a single call.

But the implementation of the `getEmailEventReportRequest()` method still limits to 100 events.
https://github.com/sendinblue/APIv3-php-library/blob/master/lib/Api/TransactionalEmailsApi.php#L2416

**Comment by preetishishodia7** [comment]
Hi @sylfabre we have recently updated doc, but our wrapper is not updated after doc, will update it soon. Thanks

**Comment by sylfabre** [comment]
Thank you @preetishishodia7 for the info.

I don't understand why you close this issue which is not solved 🤔

**Comment by preetishishodia7** [comment]
Hi @sylfabre we have created a task for the same at our end, so i guess if both things have same requirement so we can close one and can keep open one.
