### ISSUE TITLE
Unexpected long headers length, got: 646278 want: less than 4096 chars

### ISSUE THREAD

**Issue by joaquin1996** [sendinblue/APIv3-php-library#237]
https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/TransactionalEmailsApi.md#sendtransacemail

Greetings, I have a problem with a service I need to send a lot of emails that the template and contacts are already preconfigured in sendinblue, but for some reason when passing the array with all the emails or recipients that I need to be sent, it gives me this error. It seems to me that the array is too big, I have reduced it with chunk little by little until I reach a point where I don't get this error. I need to send an array with 11,200 emails so that sendinblue can send them. but the exception tells me that there is a limit of 4096 characters which is very little to send mass emails. How can I raise this limit is there any way? or some other method that can help me for my case? please I need help.

![error sendinblue](https://user-images.githubusercontent.com/49375264/195429414-4bcd56a7-7ea3-4a5e-b7fb-03247bf4803b.PNG)

**Comment by joaquin1996** [comment]
una solucion temporal que logre fue con chunk en php de esta forma reducir las solicitudes a lotes de 60 para que cumpla con el limite de 4096 caracteres 

foreach (array_chunk($destinatarios,60) as $t){
  // core
}

**Comment by mattsbennett** [comment]
We ran into this as well, starting yesterday. Seems like there must have been some validation change to the API.

Would be nice if this library provided some handling (perhaps batching internally when necessary).

**Comment by preetishishodia7** [comment]
Hi @joaquin1996 @mattsbennett , We only allow 4096 char length in headers, can you please modify your script accordingly. 
Thanks!
