### ISSUE TITLE
Webhooks API: getWebhook throws: Invalid value for 'type', must be one of 'marketing', 'transac'

### ISSUE THREAD

**Issue by VitaliiTsilnyk** [sendinblue/APIv3-php-library#243]
Looks like the [GetWebhook](https://github.com/sendinblue/APIv3-php-library/blob/master/lib/Model/GetWebhook.php#L192) model is incorrect. It expects `marketing` and `transac` as possible values for the `type` property, but the actual API returns `transactional`.

Steps to reproduce:
1. Create a webhook using the `createWebhook` request with `transactional` type, any other data seems irrelevant. Receive the webhook ID.
2. Request the webhook info using the `getWebhook` and get an exception (example below)

Exception:
```
Exception 'InvalidArgumentException' with message 'Invalid value for 'type', must be one of 'marketing', 'transac'' 

in /var/www/html/vendor/sendinblue/api-v3-sdk/lib/Model/GetWebhook.php:404

Stack trace:
#0 /var/www/html/vendor/sendinblue/api-v3-sdk/lib/ObjectSerializer.php(316): SendinBlue\Client\Model\GetWebhook-&gt;setType('transactional')
#1 /var/www/html/vendor/sendinblue/api-v3-sdk/lib/Api/WebhooksApi.php(702): SendinBlue\Client\ObjectSerializer::deserialize(Object(stdClass), '\\SendinBlue\\Cli...', Array)
#2 /var/www/html/vendor/sendinblue/api-v3-sdk/lib/Api/WebhooksApi.php(643): SendinBlue\Client\Api\WebhooksApi-&gt;getWebhookWithHttpInfo(######)
...
```

Response returned by the API:
```
{
  "url": "http://#####################",
  "id": ######,
  "description": "############",
  "events": [
    "unsubscribed"
  ],
  "type": "transactional",
  "createdAt": "2022-12-08T11:23:55.000+01:00",
  "modifiedAt": "2022-12-08T11:23:55.000+01:00"
}
```

**Comment by preetishishodia7** [comment]
Hi @VitaliiTsilnyk We have found the issue and we are working on fix. will let you know once it is fixed.

**Comment by preetishishodia7** [comment]
Hi @VitaliiTsilnyk 
We have fixed this issue in our latest SDK update i.e. `8.4.2` please use that. For now we are closing this issue.
Feel free to add if you face any issue. 
Thanks!
