### ISSUE TITLE
SendinBlue\Client\Configuration" not found

### ISSUE THREAD

**Issue by naimulkazma** [sendinblue/APIv3-php-library#250]
` 
<?php
require FCPATH . 'vendor/autoload.php';
public function sendRawPHPMail($recipient, $subject, $htmlbody, $att=""){
        //require FCPATH . 'vendor/autoload.php';
        //require_once(FCPATH . "vendor/APIv3-php-library/autoload.php");
        $config = \SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'api-key');

        $apiInstance = new \SendinBlue\Client\Api\TransactionalEmailsApi(
            new GuzzleHttp\Client(),
            $config
        );
        $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();
        $sendSmtpEmail['subject'] = $subject;
        $sendSmtpEmail['htmlContent'] =  $htmlbody;
        $sender = 'no-reply@exreed.com';
        $sendername = 'exreed';
        $sendSmtpEmail['sender'] = array('name' => $sendername, 'email' =>  $sender);
        $sendSmtpEmail['to'] = array(
            array('email' => $recipient)
        );
        if($att){
            $sendSmtpEmail['attachment'] = ['url' => $att];
             
            
        }
        // $sendSmtpEmail['cc'] = array(
        //     array('email' => 'example2@example2.com', 'name' => 'Janice Doe')
        // );
        // $sendSmtpEmail['bcc'] = array(
        //     array('email' => 'example@example.com', 'name' => 'John Doe')
        // );
        $sendSmtpEmail['replyTo'] = array('email' => $sender, 'name' => $sendername);
        $sendSmtpEmail['headers'] = array('mailId' =>  time().'-'.rand(1000, 9999));
       // $sendSmtpEmail['params'] = array('parameter' => 'My param value', 'subject' => 'New Subject');

        try {
            $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling TransactionalEmailsApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
        }
    }`

**Comment by preetishishodia7** [comment]
Hi @naimulkazma 
Can you please explain it more or it would be great if you can share error trace.
Can you please try with this example, if still face any issue please let me know will look into it. 

```
<?php
require_once(__DIR__ . '/vendor/autoload.php');

$config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR API KEY');

$apiInstance = new SendinBlue\Client\Api\TransactionalEmailsApi(
    new GuzzleHttp\Client(),
    $config
);
$sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();
$sendSmtpEmail['subject'] = 'My {{params.subject}}';
$sendSmtpEmail['htmlContent'] = '<html><body><h1>This is a transactional email {{params.parameter}}</h1></body></html>';
$sendSmtpEmail['sender'] = array('name' => 'John Doe', 'email' => 'example@example.com');
$sendSmtpEmail['to'] = array(
    array('email' => 'example1@example1.com', 'name' => 'Jane Doe')
);
$sendSmtpEmail['cc'] = array(
    array('email' => 'example2@example2.com', 'name' => 'Janice Doe')
);
$sendSmtpEmail['bcc'] = array(
    array('email' => 'example@example.com', 'name' => 'John Doe')
);
$sendSmtpEmail['replyTo'] = array('email' => 'replyto@domain.com', 'name' => 'John Doe');
$sendSmtpEmail['headers'] = array('Some-Custom-Name' => 'unique-id-1234');
$sendSmtpEmail['params'] = array('parameter' => 'My param value', 'subject' => 'New Subject');

try {
    $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling TransactionalEmailsApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
}
?>
```
You can take reference from this [link](https://developers.sendinblue.com/reference/sendtransacemail) also for better understanding. 
Thanks !
