### ISSUE TITLE
Issue about removeContactFromList api

### ISSUE THREAD

**Issue by alantran99** [sendinblue/APIv3-php-library#252]
I have a question about the removeContactFromList api; as you see, I can still use it and have it work properly.

![image](https://user-images.githubusercontent.com/87791935/217745833-3b3fbce5-0c6b-4618-a7cd-d5aebc707e2e.png)

However, I see list contacts waiting 30 seconds to 1 minute to be deleted successfully. 
It works asynchronously, right? Why does it delete everything immediately?

**Comment by preetishishodia7** [comment]
Yes, It works asynchronously and it delete whenever the given processId is picked for process.
