### ISSUE TITLE
Missing domain managements routes in the SDK

### ISSUE THREAD

**Issue by rGaillard** [sendinblue/APIv3-php-library#259]
The senders/domains routes (https://developers.sendinblue.com/reference/getdomains) seems missing into the SDK :(

**Comment by preetishishodia7** [comment]
Hi @rGaillard 
We have added these new routes  in our new [brevo-php](https://github.com/getbrevo/brevo-php) SDK which support brevo.com domain [here](https://packagist.org/packages/getbrevo/brevo-php), you can explore and use it. If you still face any issue please let us know we will look into it.
Thanks!

**Comment by rGaillard** [comment]
Hi @preetishishodia7 
This a good news! Thank you for the update :)
