### ISSUE TITLE
Methods name differences

### ISSUE THREAD

**Issue by rflorent** [sendinblue/APIv3-php-library#26]
After the symfony bundle installation, we have a difference between the api php librairy installed and the repo version, resulting in this error for the deleteEmailCampaign method :

`Attempted to call an undefined method named "deleteEmailCampaign" of class "SendinBlue\Client\Api\EmailCampaignsApi".
Did you mean to call e.g. "createEmailCampaign", "deleteEmailCampaigns", "deleteEmailCampaignsWithHttpInfo", "getEmailCampaign", "getEmailCampaigns" or "updateEmailCampaigns"?`

deleteEmailCampaign in the installation,  deleteEmailCampaigns in the repo. 
Thanks

**Comment by rflorent** [comment]
`"name": "sendinblue/api-bundle",
"version": "1.1.0",
"sendinblue/api-v3-sdk": "^2",`

**Comment by rflorent** [comment]
Updating only the api-v3-sdk and not the symfony bundle resolve it

**Comment by ekta-slit** [comment]
Hi @rflorent 

We have done some changes in spec and missed to change major version, apologies for that.
We have re-updated our releases.
You can now update the bundle to `1.2.0` and doesn't need to require `sendinblue/api-v3-sdk`

Thanks
