### ISSUE TITLE
Brevo API Endpoint migration

### ISSUE THREAD

**Issue by wearequantico** [sendinblue/APIv3-php-library#261]
Hi,
looking at the new Brevo documentation (https://developers.brevo.com/docs/how-it-works#endpoints) , it seems the new API endpoints will be

https://api.brevo.com/v3/

obviously the current endpoints are still working, but
is there an official EOS/EOL for https://api.sendinblue.com/v3/  ?
Thanks

**Comment by preetishishodia7** [comment]
Hi @wearequantico 
We have released new [brevo-php](https://github.com/getbrevo/brevo-php) SDK for brevo.com domain [here](https://packagist.org/packages/getbrevo/brevo-php), you can explore and use it. If you face any issue please let us know we will look into it.
Thanks!

**Comment by preetishishodia7** [comment]
Hi @djsunderland 
We will not bring current SIB v3 endpoint to end of life (EOL) anytime soon.
But, we will not provide with any new updates on the old SDK.
Thanks.
