### ISSUE TITLE
GetEmailCampaigns : status property not always exists in response

### ISSUE THREAD

**Issue by rflorent** [sendinblue/APIv3-php-library#28]
Hy,

When a email campaign is suspended or in a draft status, there is no status property retrieve by the GetEmailCampaigns api function.

Data return for a draft email campaign :
`"id": 5,
      "name": "Test Outlook",
      "subject": "Test Outlook",
      "type": "classic",
      "testSent": true,
      "header": "[DEFAULT_HEADER]",
      "footer": "[DEFAULT_FOOTER]",`

Data return for a suspended email campaign :
`"id": 4,
      "name": "Nouveau test newsletter",
      "subject": "Test",
      "type": "classic",
      "testSent": true,
      "header": "[DEFAULT_HEADER]",
      "footer": "[DEFAULT_FOOTER]",`

Data return for a sent email campaign :
`"id": 3,
      "name": "Campagne test 4",
      "subject": "Test 2",
      "type": "classic",
      "status": "sent",
      "testSent": true,`

Why this behavior ? how could we know the status ??
This seems like a bug.

Thanks

**Comment by ekta-slit** [comment]
Hi @rflorent 
Thanks for reporting the issue, we will improve & update.

**Comment by ekta-slit** [comment]
Issue has been fixed @rflorent.
Thanks
