### ISSUE TITLE
Create or Update

### ISSUE THREAD

**Issue by graphicgeek** [sendinblue/APIv3-php-library#29]
I'm trying to write a very simple form that takes an email from user input and adds it to a list. I have it working so long as a contact with that email doesn't already exist. If the email exists, I get a (rather descriptive) fatal error.

Is there a "create or update" method of some kind that would create a contact or update the existing contact if it exists? The previous version of the API had a method for this but I can't find anything analogous here.

**Comment by ekta-slit** [comment]
Hi @graphicgeek 

You cab achieve this functionality by using the input parameter `updateEnabled: true` in the create call itself!
Refer: https://developers.sendinblue.com/v3.0/reference#createcontact

Thanks
