### ISSUE TITLE
Export contacts

### ISSUE THREAD

**Issue by florianproxi** [sendinblue/APIv3-php-library#34]
Hello,

I want to use the method requestContactExport() to export contacts from a campaign, but i don't know how to create the object contactFilter ?

cc @ekta-slit

**Comment by florianproxi** [comment]
I found the solution, we need to pass an array like this : $requestContactExport->setContactFilter(array('blacklisted'=>1));

Not great ... It would be nice to have your APIs and documentation re-read before going into production;) We say thank you who?

cc @ekta-slit

**Comment by ekta-slit** [comment]
Hi @florianproxi 

The sample is provided here https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/ContactsApi.md#requestcontactexport and for the expected input parameters here is the description https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Model/RequestContactExport.md
Please refer the below sample.

```
$api_instance = new SendinBlue\Client\Api\ContactsApi();
$requestContactExport = new \SendinBlue\Client\Model\RequestContactExport(); // \SendinBlue\Client\Model\RequestContactExport | Values to request a contact export

$requestContactExport['contactFilter'] = array('blacklisted'=>1);

try {
    $result = $api_instance->requestContactExport($requestContactExport);
    print_r($result);
} catch (Exception $e) {
    print_r($e);
    echo 'Exception when calling ContactsApi->requestContactExport: ', $e->getMessage(), PHP_EOL;
}
```

We will try to improve our samples more if still these are not clear in near future :)
Thanks

**Comment by hervehobbes** [comment]
Hello,

Sorry for reopening this ticket but how the notify url is called?
Does it receive the CSV URL from a GET or POST?
If it's a GET, what will be the parameter(s)?

**Comment by hervehobbes** [comment]
Ok, for anyone searching for information about this subject, the response is a POST with content like this:

```
Array
(
    [proc_success] => 81
    [url] => https://api-export.sendinblue.com/upload/42389872-87a1-zc92-c849-zA133f60bcc14.csv
)

```
