### ISSUE TITLE
getEmailCampaigns returns 404 if no campaigns exist, API throws Exception

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#36]
While integrating the API in our system I stumbled across this annoyance.

The API Call getEmailCampaigns as documented here:
```https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/EmailCampaignsApi.md#getemailcampaigns```
is requesting
```https://api.sendinblue.com/v3/emailCampaigns```
which is returning *HTTP Status Code 404* when there are no campaigns yet.

Additionally the response body differs from the usual body as followed:

When there is no campaign:
```
{
  "code": "document_not_found",
  "message": "campaign do not exist"
}
```

When there is at least one campaign:
```
{
  "count": 1,
  "campaigns": [
    {
      "id": 7,
       //shortened
    }
  ]
}
```

## Expected behaviour:
* Response with *HTTP Satus Code 200* (because the list of campaigns exists even though it is empty)

* Response body with content with regular structure in this case, i.e.
```
{
  "count": 0,
  "campaigns": [ ]
}
```

Because of this behaviour the API lib is throwing an ApiException instead of returning an empty list of campaigns.

I guess - but haven't checked - this is the same for every other "get Items" call against the api.

thanks

**Comment by ekta-slit** [comment]
Hi @karsten-eger 

Thanks for reporting, we will update you once changes are live.
