### ISSUE TITLE
Model/GetEmailCampaigns count is wrong

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#38]
The count value in the Model/GetEmailCampaigns model is wrong when you use the optional filtering (by i.e. status). In our example the array with campaigns contained the correct campaigns regarding the used filter but count was always the amount of campaigns available without any filtering.

see https://github.com/sendinblue/APIv3-php-library/blob/4886771006ba38523a79c3cb218a01b9ae85156f/lib/Api/EmailCampaignsApi.php#L478

**Comment by ekta-slit** [comment]
Hi @karsten-eger 

The `count` field in response will always be the total number of Email campaigns present in the account, irrespective of the filter used. Same is the case with rest all GET calls.

Thanks

**Comment by karsten-eger** [comment]
This does not make any sense though. How am I supposed to do a paging when I have no idea how many entities the result is holding? I thought that's what "count" is for 😉

**Comment by ekta-slit** [comment]
For paging you can use `campaigns` field in response which is an array of objects ( count on that, you already have `limit` and `offset` query parameters ) and along with that we give complete `count` of campaigns as well 🙂

**Comment by karsten-eger** [comment]
> or paging you can use campaigns field in response which is an array of objects ( count on that, you already have limit and offset query parameters )
Let's do an example here:
- I have 200 campaigns in my account (55 are sent)
- I want to create a paged view with 10 (sent) campaigns on each page

With what you suggest I have no way of knowing I need 6 pages for this since the only options I have is count the entries in `campaigns` which is 10 - the limit I'm setting or use the count field, which is 200 in this case. How am I supposed to get the count of the sent campaigns (55)?
