### ISSUE TITLE
Model/CreateEmailCampaign - disable Header/Footer does not work properly

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#39]
When creating a campaign via API the setup of header and footer does not work properly. Both values are optional, so they fall back to their default_header setting configured in the gui.

Actual behaviour:
- setting header/footer to empty string ```''``` ends up changing nothing. The default header/footer is still used
- setting header/footer to whitespace string ```' '``` ends up changing nothing. The default header/footer is still used
- setting header/footer to anything else string i.e. ```something``` triggers a check if the ```[MIRRORLINK]``` is found in the body of the mail and deactivates those two values entirely - as seen in the settings screen in the dashboard gui. The string entered here is never rendered inside the mail body though! We circumvented this right now with a single empty div ```<div></div>```

Desired behaviour:
- setting to empty string via API should disable header/footer respectively
- setting whitespace string via API should disable header/footer respectively
- the check if header/footer are needed should run beforehand

**Comment by ekta-slit** [comment]
API Functionality
- setting to empty string via API uses default header/footer respectively
- setting whitespace string via API  uses default header/footer respectively
- setting header/footer to anything else i.e. `something`, then for footer default value is used ( as footer must have `[UNSUBSCRIBE]` ) & for header default value is used ( if it doesn't have `[MIRROR]`)
