### ISSUE TITLE
GetEmailCampaigns does include statistics, getEmailCampaign does not

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#40]
When retrieving several campaigns at once via the GetEmailCampaigns call the array with all the campaign data contains all the statistics data available for each campaign (GetExtendedCampaignStats Model).

Actual behaviour:
When requesting only a single campaign via GetEmailCampaign this statistics data is missing.

Desired behaviour:
When requesting only a single campaign via GetEmailCampaign this statistics data is not missing.

**Comment by ekta-slit** [comment]
This issue has been already fixed in `https://github.com/sendinblue/APIv3-php-library/releases/tag/v5.0.0`
