### ISSUE TITLE
Sending transactional email does not support setting tags

### ISSUE THREAD

**Issue by zergu** [sendinblue/APIv3-php-library#43]
There's no tags field defined here:
https://github.com/sendinblue/APIv3-php-library/blob/master/lib/Model/SendSmtpEmail.php

Therefore one can't tag outgoing emails.

**Comment by ekta-slit** [comment]
Hi @zergu 

A new parameter `tags` has been added in release [6.0.0](https://github.com/sendinblue/APIv3-php-library/releases/tag/v6.0.0)
Refer https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Model/SendSmtpEmail.md
With which you can tag your emails to find them more easily.

Thanks

**Comment by zergu** [comment]
Thanks for a quick fix, sending emails with tags now works fine, but I cannot see those in transactional logs in Sendinblue panel. Not sure if it's related though.
