### ISSUE TITLE
why caller need to provide Guzzle instance

### ISSUE THREAD

**Issue by zlaio** [sendinblue/APIv3-php-library#44]
Hey,

We noticed that you recently change your api and now it looks like:

`$apiInstance = new SendinBlue\Client\Api\SMTPApi(
   
    new GuzzleHttp\Client(),
    
    $config
);`

It's a pretty bad idea that caller has to provide a guzzle instance in an API. It should be done by SDK itself. Totally strange to me.

**Comment by ekta-slit** [comment]
Hi @zlaio 

Yes we had recently updated our php wrapper with `swagger-codegen` version `2.3.1`, which is a major release and is using `GuzzleHttp` as a dependency.
So new API samples have this improvement.

Thanks
