### ISSUE TITLE
Can't get smtp activities with tags in getEmailEventReport()

### ISSUE THREAD

**Issue by zergu** [sendinblue/APIv3-php-library#45]
Hi, this is probably related to #43 

```
In ObjectSerializer.php line 264:
                                      
  Notice: Array to string conversion
```

**Comment by ekta-slit** [comment]
Thanks for reporting the issue @zergu 
We will update with the fix shortly

**Comment by ekta-slit** [comment]
Issue has been fixed, FYI records with multiple tags will be shown as comma separated string.
Thanks

**Comment by zergu** [comment]
@ekta-slit Thanks, it works fine now.
