### ISSUE TITLE
Problem with dates in getEmailEventReport() 

### ISSUE THREAD

**Issue by zergu** [sendinblue/APIv3-php-library#46]
When passing DateTime to getEmailEventReport() with startDate or endDate parameters they are converted to DateTime::ATOM format which is not supported in this API call. It probably should be just Y-m-d format.

```
{
  "code": "invalid_parameter",
  "message": "Start date is not valid"
}
```

**Comment by ekta-slit** [comment]
Yes @zergu you are right, please use start and end date just as strings, for example mentioned below to get good results.

```
$startDate = '2018-05-24';
$endDate = '2018-05-28';
```

We will re-check our specification to do this fix for such dates type definitions.
Thanks

**Comment by zergu** [comment]
Yeah, I did that yesterday as a workaround, but I think is still should be fixed because 

>   * @param  \DateTime $startDate Mandatory if endDate is used. Starting date of the report (YYYY-MM-DD). Must be lower than equal to endDate (optional)
     * @param  \DateTime $endDate Mandatory if startDate is used. Ending date of the report (YYYY-MM-DD). Must be greater than equal to startDate (optional)
