### ISSUE TITLE
getContacts -> modifiedSince changes even on "touch" only

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#49]
Hey,

I'm not quite sure if this is the right place, but within the dashboard would be as false as here. 😉 

It seems like the 'modifiedSince' attribute is changed everytime the contact is touched - i.e. through a dynamic list.

As we syncronize our data we noticed that everytime the dynamic lists kick in, the sync is trying to update a whole bunch of contacts even though this is not necessary. A contact thats checked for this dynamic lists and is not changed in any way should not get a new timestamp for modifiedSince.

thx

**Comment by rajatsib** [comment]
Hi @karsten-eger 

If you create a list and add the contact to that list, then the contact is modified since we maintain that the contact was added to a particular list.

**Comment by rajatsib** [comment]
Closing this issue
