### ISSUE TITLE
SendSmtpEmail - Enable using templateId AND attachment

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#50]
Right now it's not possible to use a templateID and add an attachment.

It would be great if this could be possible.

thx!

**Comment by JuanLeadSupply** [comment]
It should work. 

I tested this feature around one month ago with the version 6.0.0 of this library and it worked for me.

You have to be sure that file extension is allowed:
https://developers.sendinblue.com/v3.0/reference#sendtemplate

and also you should to encode the file, like in the following example code:

```
            $content = chunk_split(base64_encode(file_get_contents($filepath)));
            $attachment[] = new SendSmtpEmailAttachment(['content' => $content, 'name' => $filename]);
            $mailer->setAttachment($attachment);
```

**Comment by karsten-eger** [comment]
hm, interesting! It's even in the documentation:
see attachment
``( Ignored if 'templateId' is passed )``
https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Model/SendSmtpEmail.md

**Comment by JuanLeadSupply** [comment]
Karsten, you are right, the attachments doesn't with templates

I have tested a few minutes ago with my [own library](https://github.com/juanparati/Sendinblue) and it doesn't work, however I implemented the functionality for attachments (Maybe in the future...).

**Comment by rajatsib** [comment]
Hi @karsten-eger @JuanLeadSupply 

If templateId is passed and is in New Template Language format then both attachment url and content are accepted. If template is in Old template Language format, then attachment is ignored

See [here ](https://developers.sendinblue.com/reference#sendtransacemail)
