### ISSUE TITLE
smtpBlacklistSender value is now required by Sendinblue as an empty Array

### ISSUE THREAD

**Issue by JuanLeadSupply** [sendinblue/APIv3-php-library#53]
Yesteday around 2018-07-09 11:12:00 CEST Sendinblue modified the behavior of the https://api.sendinblue.com/v3/contacts end-point.

It seems that smtpBlacklistSender value cannot be assigned as "null" anymore so the following error was received by the service:

`{\"code\":\"invalid_parameter\",\"message\":\"Invalid smtpBlacklistSender format\"}`

I was not assigning the value for "smtpBlacklistSender", so I figure out that maybe the APIv3-php-library was doing it.

I found that CreateContact model is assigning "smtpBlacklistSender" a null value instead an empty array:

`$this->container['smtpBlacklistSender'] = isset($data['smtpBlacklistSender']) ? $data['smtpBlacklistSender'] : null;`

I observed that the swagger definition was correct, and in fact I was running my code during weeks using smtpBlacklistSender as null without notice any error, so I figure out that something changed in the behaviour of the https://api.sendinblue.com/v3/contacts endpoint. 

Steps to reproduce:

1. Push new contact with updateEnabled and without smtpBlacklistSender:
```
 $subscription_body =
        [
            'email'               => $email,
            'emailBlacklisted'    => false,
            'smsBlacklisted'      => false,
            'listIds'             => [1, 2, 3],
            'attributes'          => ['NAME' => 'Test'],
            'updateEnabled'       => true,
        ];

$contact_api->createContact(new CreateContact($subscription_body));
```
Expected result:

Contact should be accepted without problems even with smtpBlacklistSender as null like it was working during the last weeks.

Received result:

`{\"code\":\"invalid_parameter\",\"message\":\"Invalid smtpBlacklistSender format\"}`

**Comment by JuanLeadSupply** [comment]
As temporal workaround in my code I am assigning smtpBlacklistSender as an empty array.

Example:

$subscription_body =
        [
            'email'               => $email,
            'emailBlacklisted'    => false,
            'smsBlacklisted'      => false,
            'listIds'             => [1, 2, 3],
            'attributes'          => ['NAME' => 'Test'],
            'updateEnabled'       => true,
            'smtpBlacklistSender' => [],
        ];

**Comment by houdheyfa** [comment]
Hello,

I have the same problem. Do you find the issue  with the updateContact method ?

Thank you

**Comment by karsten-eger** [comment]
same here!

**Comment by ekta-slit** [comment]
Hello

Thanks for reporting the issue. Its had been fixed on 12th july at 15:47 IST.
No changes done on `sendinblue/api-v3-sdk`, just the internal code.

Please check, issue is no more!

Thanks
