### ISSUE TITLE
Get with Resultlist and Count

### ISSUE THREAD

**Issue by karsten-eger** [sendinblue/APIv3-php-library#55]
This seems to affect all Get-Calls with a result-list in the response.

As suggested in #38 the count in the Get-Calls is useless as it is. Now we noticed this with getContacts as well. I don't know when the change occured but now ``count``does not contain the amount of items in the resultlist (with modifiedsince filter) anymore. Instead it's the amount of all contacs regardless of the filtering criteria.

As stated in #38 there now is no way in knowing how many runs a cronjob needs to make or how many pages I need to display in a GUI. Instead I need to loop until the entity array is empty. (see https://github.com/sendinblue/APIv3-php-library/issues/38#issuecomment-391252890 )
This does not make any sense.

Please change the count value so it accounts for the total amount of entities the filtering is matching or add a second count which does exactly this.

**Comment by Mahima-eng** [comment]
Hi @karsten-eger ,
The count field will always show the total count in the response body. The logic behind it is that you can apply limit and offset accordingly until to reach the count i.e. the total resources available.

Thanks
