### ISSUE TITLE
API v3 Create SMS Campaign

### ISSUE THREAD

**Issue by jbrat** [sendinblue/APIv3-php-library#57]
Hello, 

I have an error when i try to use the createSMSCampaign function in the API, i saw in the documentation of API V3 Sendinblue the SMS Campaign haven't been developed.

Have you got any ideas when the functionnality will be done ?

**Comment by ekta-slit** [comment]
Hi @jbrat 

It will be released by the end of September.
Please refer https://developers.sendinblue.com/docs/change-log

Thanks
