### ISSUE TITLE
How to pass accented characters int CreateContact ?

### ISSUE THREAD

**Issue by chatlumo** [sendinblue/APIv3-php-library#62]
Hello,

How is it possible to pass accented characters int CreateContact method ?
By example i have an attribute PRENOM. If the value is "Léa", how to encode it ?

Because for now, it returns an error : [400] Error connecting to the API (https://api.sendinblue.com/v3/contacts)

I tried with urlencode() but with that, this attribute = "L%E9a+" in the dashboard.

**Comment by ThomasBarnekow** [comment]
@chatlumo Did you try to add `charset=utf-8` to the content type? Not sure whether that helps, though.

**Comment by rajatsib** [comment]
Hi @chatlumo 

You can send it as a string without encoding.
