### ISSUE TITLE
getContactStats()

### ISSUE THREAD

**Issue by florianproxi** [sendinblue/APIv3-php-library#63]
Hello

I would like to know if it will be possible to recover the campaigns, in addition to the id campaign, with the method getContactStats ()?

Thanks

**Comment by rajatsib** [comment]
Hi @florianproxi 

Only campaign id is returned in getContactStats
To fetch the complete information of campaigns, please use [getEmailCampaign](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/EmailCampaignsApi.md#getemailcampaign)
