### ISSUE TITLE
Can't delete contacts with deleteContact()

### ISSUE THREAD

**Issue by hervehobbes** [sendinblue/APIv3-php-library#64]
Hello,

I try to remove, from our contacts list, the people who unsubscribed to our mailing list.
I'm using this code to do so:

`$apiInstance->deleteContact($email);`

I often have some error messages like this:

`Exception when calling ContactsApi->deleteContact: [404] Client error: `DELETE https://api.sendinblue.com/v3/contacts/bill%40exmaple.com` resulted in a `404 Not  Not Found` response: {"code":"document_not_found","message":"Contact does not exist"}`

Except that I got the email address from this method:
`
$requestContactExport = new \SendinBlue\Client\Model\RequestContactExport();
$requestContactExport->setNotifyUrl(NOTIFY_URL);
`

With this filter:
`$requestContactExport->setContactFilter(['blacklisted' => 1]);`

I have tried to use rawurlencode() and urlencode() (and nothing) on the email address but this does not change anything.

Any suggestion?

**Comment by ekta-slit** [comment]
Hi @hervehobbes
If thats the case, please raise a support request here https://account.sendinblue.com/support

Thanks
