### ISSUE TITLE
Documentation is very poor. I had to figure out options from source.

### ISSUE THREAD

**Issue by drnkwati** [sendinblue/APIv3-php-library#66]
Please improve docs.
Simple stuff such as sending transnational emails should not be a problem.
When creating SendSmtpEmail for example:
`new \SendinBlue\Client\Model\SendSmtpEmail()`
what goes in to constructor SendSmtpEmail? i had to dig in the source code to figure that out.
At least provide defaults options in readme and not just leave it blank there.
Its also a bad idea to start changing well accepted options for emails like from to sender.
Changes like this just start confusing developers.
Lets be consistent as most email APIs use from not sender.

thanks

**Comment by ekta-slit** [comment]
Hi @drnkwati 

Thanks for sharing your feedback.
We are already working on API Doc improvement, will be live soon with the samples having default values to execute an API.

Thank you

**Comment by COil** [comment]
+1 I had the same problem. An example with every possible option passed the container array should be added. We alos don't know it a "Model" must be used or raw values as array.
