### ISSUE TITLE
 Error 500 with sendTransacEmail()

### ISSUE THREAD

**Issue by proximiteclient** [sendinblue/APIv3-php-library#68]
Dear,
I have an error 500 without detailed when i called sendTransacEmail(). Any idea ?

[500] Server error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `500 Internal Server Error` response:
{}

**Comment by rajatsib** [comment]
Hi @proximiteclient 

A 500 internal server error occurs when there is an issue while processing the request on server's end.
Can you please share the some timeframe in which we can check?

**Comment by Yordi93** [comment]
[2020-08-05 12:09:21] local.ERROR: [502] Server error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `502 Bad Gateway` response:
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link href="https:// (truncated...)
 {"userId":2,"email":"facturacion@condominiocampestreelpenon.com","exception":"[object] (SendinBlue\\Client\\ApiException(code: 502): [502] Server error: `POST 
 https://api.sendinblue.com/v3/smtp/email` resulted in a `502 Bad Gateway` response:
<!DOCTYPE html>
<html>
<head>
<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />
<link href=\"https:// (truncated...)
 at /var/www/html/horus/vendor/sendinblue/api-v3-sdk/lib/Api/SMTPApi.php:2999)
[stacktrace]

**Comment by Yordi93** [comment]
![image](https://user-images.githubusercontent.com/1544274/89447525-b50f7780-d71b-11ea-85f0-d8f0ec37412f.png)

**Comment by rajatsib** [comment]
Hi @Yordi93 

This seems like an intermittent issue due to infrastructure. Are you still receiving these errors frequently ?

**Comment by rajatsib** [comment]
Closing this thread as this was an intermittent issue

Thanks

**Comment by speriosu** [comment]
Seeing this same problem (500 response code from sendTransacEmail) since about 8am Pacific this morning.
