### ISSUE TITLE
Set headers on SendSmtpEmail

### ISSUE THREAD

**Issue by lcampanari** [sendinblue/APIv3-php-library#76]
Hi, I'm trying to setup the headers on SendSmtpEmail. The [documentation](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Model/SendSmtpEmail.md) says that `headers` is supposed to be of type `object`. However, I can't seem to make this work. Here's what I tried:

1) `$headers = "{'Content-Type':'text/html', 'charset':'iso-8859-1', 'sender.ip':'x.x.x.x'}";`
1) `$headers =  json_encode(['Content-Type'=>'text/html', 'charset'=>'iso-8859-1', 'sender.ip'=>'x.x.x.x']);`
1) `$headers = "{'sender.ip':'x.x.x.x'}";`
1) `$headers =  json_encode(['sender.ip'=>'x.x.x.x']);`

```
        $dataSmtpEmail['headers'] = $headers;
        $dataSmtpEmail['htmlContent'] = $data['htmlContent'];
        $dataSmtpEmail['subject'] = $data['subject'];
        $dataSmtpEmail['tags'] = $data['tags'];
        $dataSmtpEmail['params'] = $data['params'];
        $dataSmtpEmail['sender'] = new \SendinBlue\Client\Model\SendSmtpEmailSender([
            'name' =>$data['sender']['name'],
            'email' =>$data['sender']['email'],
        ]);
        $dataSmtpEmail['replyTo'] = new \SendinBlue\Client\Model\SendSmtpEmailReplyTo([
            'name' =>$data['sender']['name'],
            'email' =>$data['sender']['email']
        ]);
        $dataSmtpEmail['to'] = [
            new \SendinBlue\Client\Model\SendSmtpEmailTo(['email' => $data['email']])
        ];
        $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail($dataSmtpEmail);
        try {
            return $apiInstance->sendTransacEmail($sendSmtpEmail);
        } catch (Exception $e) {
            return false;
        }
```
All of the trials above yields the following: 
> [400] Client error: `POST https://api.sendinblue.com/v3/smtp/email` resulted in a `400 Bad Request` response: {"code":"invalid_parameter","message":"Invalid headers"}

If I don't set the headers it will work, but the email will be sent through the wrong dedicated IP.

Could someone please provide a valid example to illustrate how to set this up? Thanks!

**Comment by lcampanari** [comment]
I also tried:
`5\. $headers =  ['Content-Type'=>'text/html', 'charset'=>'iso-8859-1', 'sender.ip'=>'x.x.x.x']`

The email is sent without errors, but the values on $headers have no effect.

**Comment by rajatsib** [comment]
Hi @lcampanari 

The ip passed in the request should be added as a dedicated IP in your Sendinblue account. 
Otherwise, the platform will use it's default ip.
