### ISSUE TITLE
Get stats of campaign A/B Test

### ISSUE THREAD

**Issue by proximiteclient** [sendinblue/APIv3-php-library#79]
Dear, 

I have implemented the function A/B Testing in my developement, but now i want get the result of the AB Test and retrieve the winner subject.

Thanks for your help

**Comment by rajatsib** [comment]
Hi @proximiteclient 

You should use [getABTestCampaignResult](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/EmailCampaignsApi.md#getabtestcampaignresult) method to fetch this data.
