### ISSUE TITLE
SMS failures not throwing Exception

### ISSUE THREAD

**Issue by unfrgivn** [sendinblue/APIv3-php-library#84]
Using this method https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/TransactionalSMSApi.md#sendtransacsms

Sending transactional SMS that bounce or are blocked are returning a successful data object. They should throw an Exception with a proper message. From the straight API docs, it appears this should return a 400 (https://developers.sendinblue.com/reference#sendtransacsms-1)

**Comment by rajatsib** [comment]
Hi @unfrgivn 

A 400 will be returned for the cases where any parameter is missing or invalid (like `invalid_phone_number` or 'content is missing').
Sending an sms is an asynchronous process.
To fetch the blocked or bounced sms, you should refer to 
https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/TransactionalSMSApi.md#getsmsevents
