### ISSUE TITLE
How to send attributes ? 

### ISSUE THREAD

**Issue by Noido** [sendinblue/APIv3-php-library#85]
Hello just installer lib and i face a problem i want to send register email to a new user register on site with a template, this user is not in my contacts list on sendinblue so i do : 

 $sendEmail = new SendEmail();

 $sendEmail->setEmailTo(["user@user.com"]);
 $sendEmail
            ->setReplyTo("email@company.com")
            ->setAttributes($attributes);

But i have no idea how create attributes  i try $attributes = ["WELCOME" => "test"] but not work mail is empty from attribute welcome

In my template on sendinblue i put {{ WELCOME }} i try to {{ contact.WELCOME }} but not work too

Can you help me thanks

**Comment by Reforced** [comment]
In my templates I'm using `%WELCOME%`. You might want to try that. [Reading up](https://help.sendinblue.com/hc/en-us/articles/360000268730-Using-SendinBlue-s-New-Template-Language-to-create-email-templates-and-campaigns-NEW-) on the new template tags `{{ params.WELCOME }}` should also work.

**Comment by ankitvadariya** [comment]
@Reforced @Noido  for Transactional email `%WELCOME%` will work in API V3. but if you want to use contact params then you can use it `{{ contact.FNAME }}` but if its **Transactional Attributes ** then you need to use `%ATTRIBUTE NAME% inside the tamplate.

**Comment by rajatsib** [comment]
Hi @Noido 

You can use the steps sepcified by @ankitvadariya [here](https://github.com/sendinblue/APIv3-php-library/issues/85#issuecomment-517337099)
