### ISSUE TITLE
CreateContact returns null and not a CreateUpdateContactModel

### ISSUE THREAD

**Issue by Evaske** [sendinblue/APIv3-php-library#88]
Hello,

I am having issues with the `createContact()` method. It is returning null instead of a `CreateUpdateContactModel` as it should be. 

    public function addEmailToList($email, $list, $name = '')
      {
        $contact = new CreateContact();
        $contact->setEmail($email);
        $contact->setListIds([$list]);
        $contact->setUpdateEnabled(true);
        $contact->setAttributes([
          'FNAME' => $name,
        ]);

        dd($this->contactsApi->createContact($contact));
      }

On looking through the source code, it seems to either get a 204 response code if it is updated or a 201 if it is created.

Should we just assume that if it is null then it has updated the contact and if it returns an id it has added them?

**Comment by rfaivre** [comment]
Any update?

**Comment by tristanleboss** [comment]
Any news? The response body from the API is empty (at least as seen by Guzzle).

**Comment by Nikoms** [comment]
Same problem with "other" libraries (nodejs). I think it happens when the contact already exist, but I'm not sure :(
