### ISSUE TITLE
SendInBlue create contact error

### ISSUE THREAD

**Issue by pirmax** [sendinblue/APIv3-php-library#9]
I'm working in local to test SendInBlue create contact.

```
Swagger\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', env('SENDINBLUE_API_KEY'));

$api_instance = new Swagger\Client\Api\ContactsApi();
$createContact = new Swagger\Client\Model\CreateContact();

$createContact['email'] = 'email@gmail.com';
$createContact['listIds'] = 2;

$result = $api_instance->createContact($createContact);

dd($result);
```
I have this error...

> [400] Error connecting to the API (https://api.sendinblue.com/v3/contacts)

**Comment by ekta-slit** [comment]
Hello @pirmax 

FYI please update the library as we have done some minor fixes.
After that for create contact AIP I suggest you to use below sample code:

`Sendinblue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', env('SENDINBLUE_API_KEY'));

$api_instance = new Sendinblue\Client\Api\ContactsApi();
$create_contact = new \Sendinblue\Client\Model\CreateContact();

$create_contact['email'] = 'email@gmail.com';
$create_contact['listIds'] = array(2);

try {
    $result = $api_instance->createContact($create_contact);
    print_r($result);
} catch (Exception $e) {
    print_r($e);
    echo 'Exception when calling ContactsApi->createContact: ', $e->getMessage(), PHP_EOL;
}`

Where `print_r($e);` will give you complete `ApiException Object`
Thanks

**Comment by bjornbos** [comment]
What about custom attributes? When I add 

    $create_contact['attributes'] = array('some_attribute' => 'some value')

I get the 400 error again.

**Comment by bjornbos** [comment]
I've also tried to wrap it as a json object:

    $create_contact['attributes'] = json_encode(array('some_attribute' => 'some value'))

The contact is then saved, but not the attributes.

**Comment by stefanogit** [comment]
I'm trying to to add an attribute value but nothing... any solutions?

**Comment by Faab** [comment]
I got this error because contact already exists in another list. The error message is not clear.
Add parameter updateEnabled = true solved the problem.

https://developers.sendinblue.com/v3.0/reference#createcontact

**Comment by devNicolasNmk** [comment]
hello,

I have the same problem with attributes. 

email is ok but attributes are not send 

any idea please ?

> 
> I've also tried to wrap it as a json object:
> 
> ```
> $create_contact['attributes'] = json_encode(array('some_attribute' => 'some value'))
> ```
> 
> The contact is then saved, but not the attributes.

**Comment by bjornbos** [comment]
I just ditched the PHP SDK and use the REST api directly. Works so much better.

**Comment by devNicolasNmk** [comment]
@bjornbos 
Thank you for your fast answer.

**Comment by karelbyte** [comment]
hello, has one managed to send the attributes?, only the email is saved

**Comment by karelbyte** [comment]
yo, envio en el data de esta manera y no guarda los atributos:
{"email":"ssss@gmail.com","attributes":{"FNAME":"sdgsfdgsdsf"}}

**Comment by korynorthrop** [comment]
I have been able to get _some_ attributes to save, but am struggling to set attributes with the "Category" type (e.g. the default `DOUBLE_OPT-IN` attribute and a custom attribute I created called `IS_SUPPORTER`, both of which are "Category" attribute types with two potential values "Yes" and "No").

I was originally struggling to set the first and last name attributes for a contact because I was following the documentation, which shows those attributes as `FNAME` and `LNAME`, but I saw in the attributes table that they are actually `FIRSTNAME` and `LASTNAME`.  The following code successfully sets the the first name and the `GDPR_CONSENT` attribute (boolean type), but doesn't update my custom category attribute (`IS_SUPPORTER`) or the native `DOUBLE_OPT-IN` category attribute.

```
$apiInstance = new SendinBlue\Client\Api\ContactsApi(
  new GuzzleHttp\Client(),
  $config
);

$email = 'testcontact@email.com';

$updateContact = new \SendinBlue\Client\Model\UpdateContact();

$updateContact['attributes'] = array(
	'FIRSTNAME' => 'Joe',
	'IS_SUPPORTER' => 'YES',
	'DOUBLE_OPT-IN' => 'NO',
	'GDPR_CONSENT' => true
);

try {
  $result = $apiInstance->updateContact( $email, $updateContact );
  var_dump( 'sent' );
} catch ( Exception $e ) {
  echo 'Exception when calling ContactsApi->createContact: ', $e->getMessage(), PHP_EOL;
}
