### ISSUE TITLE
Time Out getLists

### ISSUE THREAD

**Issue by BoutiquesInternet** [sendinblue/APIv3-php-library#91]
Hi,

Sometimes I have a time out like this. It happens a lot actually.

`Exception when calling ContactsApi->getLists: [524] Server error: `GET https://api.sendinblue.com/v3/contacts/lists?limit=50&offset=0` resulted in a `524 Origin Time-out` response:`

How can I avoid that?

**Comment by rajatsib** [comment]
Hi @BoutiquesInternet 

We have made some improvements in this route. Do let us know if you still face issues with this route.

**Comment by thomaslemoine** [comment]
I have the same problem with the first call.

Symfony : 5.2.6
sendinblue/api-v3-sdk: 7.4.0

**Comment by marshall76963** [comment]
Hi

Facing a similar problem with calls to CreateContact (from cold) using .Net wrapper.

sib_api_v3_sdk : 3.2.0

```html
sib_api_v3_sdk.Client.ApiException: Error calling CreateContact: <!DOCTYPE html>
<!--[if lt IE 7]> <html class (truncated...)> <!--<![endif]-->
<head>
<title>api.sendinblue.com | 522: Connection timed out</title>
...
```
