### ISSUE TITLE
Sendinblue server date?

### ISSUE THREAD

**Issue by NeftaliAcosta** [sendinblue/APIv3-php-library#93]
How can I get the local time from the server? I am using the getEmailEventReport function, but in my country (for example), it is still October 18, 2019 and on the server it is already October 19, 2019, I cannot get the actual data of the day.

How can I define this data correctly?

Thank you.

**Comment by rajatsib** [comment]
Hi @NeftaliAcosta

The dates passed in the response of this endpoint are in UTC and data is returned for a UTC day
