### ISSUE TITLE
Integration with Laravel

### ISSUE THREAD

**Issue by ZephiroRB** [sendinblue/APIv3-php-library#94]
There is documentation to implement  sendinblue with laravel?

**Comment by RobinTHOREL** [comment]
just why do you need a specific doc for laravel dude

**Comment by metalcamp** [comment]
@CarlangasGO you shouldn't have any trouble implementing wrapper in your Laravel app with existing documentation. Or simply use [vansteen/laravel-sendinblue](https://packagist.org/packages/vansteen/laravel-sendinblue) provider.
