### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by Trazmor** [sendinblue/APIv3-php-library#95]
Hello,
I don't have SSH access on my website, how can I install sendinblue php API ?
Thanks

**Comment by rajatsib** [comment]
Hello @Trazmor 

You can use composer to install Php Library
Follow the steps mentioned in readme [here ](https://github.com/sendinblue/APIv3-php-library) .
If you face any issues, feel free to comment here

**Comment by Shahreyar46** [comment]
Hello how can i use this library  without composer.

**Comment by EvansPM** [comment]
Yes would be nice to have another way to install sendinblue php without Composer.
I use shared hosting service with any way to run a terminal in order to use Composer and no SSL access.
Just download the file them copy it to server would be very appreciated.
