### ISSUE TITLE
Create a new contact in a list

### ISSUE THREAD

**Issue by alexandra-toder** [sendinblue/APIv3-php-library#98]
I tried to create the new contact to a list ID using the API "https://api.sendinblue.com/v3/contacts" and passed the "listIds" => [7], but I get the error "[400] Client error: `POST https://api.sendinblue.com/v3/contacts` resulted in a `400 Bad Request` response: {"code":"invalid_parameter","message":"Contact already exist"} " on line 701 of C:\xampp\htdocs\TIZOUTI\tizouti-web\vendor\sendinblue\api-v3-sdk\lib\Api\ContactsApi.php" because the user existing in other list
Please let me know, if you have any solution for it. Or how can check if the contact exist in PHP?
Thanks.

**Comment by metalcamp** [comment]
You can check if contact already exists using [getContactInfo](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/ContactsApi.md#getcontactinfo).

**Comment by rajatsib** [comment]
Hi @alexandra-toder 

If you want to add a contact to a list which already exists, you can do it using [AddContactToList](https://github.com/sendinblue/APIv3-php-library/blob/master/docs/Api/ContactsApi.md#addcontacttolist) endpoint
